/**
 * `ESP-20` — o baralho de dicas de pergunta do Espião.
 *
 * Sorteio 100% local, sem round-trip: nenhuma dica é ligada ao local sorteado,
 * e é justamente por isso que ela pode viver no cliente sem ferir `AD-003`. A
 * lista é grande de propósito — com quinze perguntas a mesa decorava o baralho
 * em duas partidas e a dica virava assinatura de quem estava travado.
 *
 * Toda pergunta aqui obedece a mesma regra: **serve pra qualquer lugar**. Uma
 * pergunta que só faz sentido num hospital entrega o local pra quem escuta.
 */
export const DICAS_DE_PERGUNTA: readonly string[] = [
  // — o que você faria aqui —
  'O que você faria aqui num dia comum?',
  'Você viria aqui de manhã ou de noite?',
  'Você viria sozinho ou acompanhado?',
  'Quanto tempo você aguentaria ficar aqui?',
  'Você já veio aqui esta semana?',
  'Você vem aqui por obrigação ou por vontade?',
  'Você viria aqui num feriado?',
  'Você marcaria um encontro aqui?',
  'Você traria seu chefe aqui?',
  'Você traria sua sogra aqui?',
  'Você traria uma criança pequena pra cá?',
  'Você traria um cachorro pra cá?',
  'Você viria aqui de novo amanhã?',
  'Você já quis ir embora daqui antes da hora?',
  'Você chegaria atrasado aqui sem problema?',
  'Você viria aqui doente?',
  'Você viria aqui só pra passar o tempo?',
  'Você entraria aqui sem avisar ninguém?',
  'Você sairia daqui correndo por algum motivo?',
  'Você voltaria aqui pra buscar algo esquecido?',

  // — o lugar em si —
  'Esse lugar é coberto ou ao ar livre?',
  'Esse lugar é grande ou apertado?',
  'Esse lugar é claro ou escuro?',
  'Esse lugar é limpo?',
  'Esse lugar é barulhento?',
  'Esse lugar tem cheiro característico?',
  'Esse lugar tem cheiro bom?',
  'Esse lugar é quente ou frio?',
  'Esse lugar tem ar-condicionado?',
  'Esse lugar tem janela?',
  'Esse lugar tem mais de um andar?',
  'Esse lugar tem escada?',
  'Esse lugar tem elevador?',
  'Esse lugar tem banheiro decente?',
  'Esse lugar tem estacionamento?',
  'Esse lugar tem fila?',
  'Esse lugar tem música tocando?',
  'Esse lugar tem televisão ligada?',
  'Esse lugar tem espelho?',
  'Esse lugar tem tapete ou carpete?',
  'Esse lugar tem plantas?',
  'Esse lugar tem cadeira confortável?',
  'Esse lugar tem parede pintada de alguma cor forte?',
  'Esse lugar tem chão duro?',
  'Esse lugar tem teto alto?',
  'Esse lugar tem porta que tranca?',
  'Esse lugar tem câmera?',
  'Esse lugar tem placa na entrada?',
  'Esse lugar tem recepção?',
  'Esse lugar tem sinal de celular?',
  'Esse lugar tem Wi-Fi?',
  'Esse lugar tem tomada disponível?',
  'Esse lugar tem lixeira à vista?',
  'Esse lugar tem relógio na parede?',
  'Esse lugar tem alguma coisa quebrada?',
  'Esse lugar precisa de reforma?',
  'Esse lugar mudou muito nos últimos anos?',
  'Esse lugar existe há muito tempo?',
  'Esse lugar existe em toda cidade?',
  'Esse lugar existe fora do Brasil também?',

  // — gente —
  'Quantas pessoas costumam estar aqui?',
  'Tem alguém trabalhando aqui agora?',
  'Tem alguém uniformizado aqui?',
  'Tem alguém aqui que manda nos outros?',
  'Tem criança aqui?',
  'Tem idoso aqui?',
  'Tem gente dormindo aqui?',
  'Tem gente comendo aqui?',
  'Tem gente com pressa aqui?',
  'Tem gente esperando alguma coisa aqui?',
  'Tem gente rindo aqui?',
  'Tem gente chorando aqui?',
  'Tem gente gritando aqui?',
  'Tem gente calada aqui?',
  'Tem gente no celular aqui?',
  'Tem gente tirando foto aqui?',
  'Tem gente bebendo aqui?',
  'Tem gente sozinha aqui?',
  'Tem gente em grupo aqui?',
  'Tem gente que não devia estar aqui?',
  'As pessoas aqui se conhecem?',
  'As pessoas aqui estão felizes?',
  'As pessoas aqui estão cansadas?',
  'Você conhece alguém que trabalha num lugar desses?',
  'Alguém da sua família já esteve aqui?',
  'Você encontraria um conhecido aqui por acaso?',

  // — dinheiro e regras —
  'Precisa pagar pra entrar aqui?',
  'Precisa de ingresso?',
  'Precisa marcar hora?',
  'Precisa de documento pra entrar?',
  'Precisa de convite?',
  'Precisa de senha?',
  'Precisa fazer fila?',
  'Aqui se gasta muito dinheiro?',
  'Dá pra pagar em dinheiro aqui?',
  'Tem gorjeta envolvida?',
  'Tem alguma regra que todo mundo segue aqui?',
  'Tem algo proibido aqui?',
  'Dá pra fumar aqui?',
  'Dá pra falar alto aqui?',
  'Dá pra correr aqui?',
  'Dá pra tirar foto aqui?',
  'Dá pra entrar de chinelo aqui?',
  'Dá pra entrar sem camisa aqui?',
  'Tem alguém checando quem entra?',
  'Você seria expulso daqui por alguma coisa?',

  // — roupa e corpo —
  'Que roupa você usaria pra vir aqui?',
  'Você viria de terno aqui?',
  'Você viria de pijama aqui?',
  'Você viria de biquíni ou sunga aqui?',
  'Você precisaria de casaco aqui?',
  'Você precisaria de calçado fechado aqui?',
  'Você precisaria de capacete aqui?',
  'Você precisaria de máscara aqui?',
  'Você precisaria de luva aqui?',
  'Você se arrumaria pra vir aqui?',
  'Você tomaria banho antes de vir?',
  'Você tomaria banho depois de sair daqui?',
  'Você ficaria em pé ou sentado a maior parte do tempo?',
  'Você andaria muito aqui?',
  'Você suaria aqui?',
  'Você passaria frio aqui?',
  'Seus pés doeriam no fim?',
  'Você sairia daqui sujo?',
  'Você sairia daqui com fome?',
  'Você sairia daqui cansado?',

  // — o que se faz —
  'Dá pra comer alguma coisa aqui?',
  'Dá pra beber alguma coisa aqui?',
  'Dá pra dormir aqui?',
  'Dá pra trabalhar aqui?',
  'Dá pra estudar aqui?',
  'Dá pra namorar aqui?',
  'Dá pra brigar aqui?',
  'Dá pra chorar aqui sem chamar atenção?',
  'Dá pra ficar horas sem fazer nada aqui?',
  'Dá pra ler um livro aqui?',
  'Dá pra ouvir música no fone aqui?',
  'Dá pra conversar sem ser interrompido aqui?',
  'Dá pra se esconder aqui?',
  'Dá pra se perder aqui?',
  'Dá pra fazer amizade aqui?',
  'Dá pra comprar alguma coisa aqui?',
  'Dá pra vender alguma coisa aqui?',
  'Dá pra pedir ajuda aqui?',
  'Dá pra assistir alguma coisa aqui?',
  'Dá pra jogar alguma coisa aqui?',

  // — objetos e cheiros —
  'Tem cadeira aqui?',
  'Tem mesa aqui?',
  'Tem cama aqui?',
  'Tem máquina fazendo barulho aqui?',
  'Tem ferramenta aqui?',
  'Tem computador aqui?',
  'Tem papel aqui?',
  'Tem caneta aqui?',
  'Tem comida à vista aqui?',
  'Tem água disponível aqui?',
  'Tem cheiro de comida aqui?',
  'Tem cheiro de produto de limpeza aqui?',
  'Tem cheiro de mofo aqui?',
  'Tem alguma coisa que eu possa levar daqui?',
  'Tem alguma coisa perigosa aqui?',
  'Tem alguma coisa cara aqui?',
  'Tem alguma coisa velha aqui?',
  'Tem alguma coisa que você levaria pra casa?',
  'Tem algum objeto que só existe aqui?',
  'Tem algum barulho que só existe aqui?',

  // — tempo e sensação —
  'Que horas esse lugar fica mais cheio?',
  'Esse lugar funciona de madrugada?',
  'Esse lugar funciona no domingo?',
  'Esse lugar fecha em algum momento?',
  'Você viria aqui na chuva?',
  'Você viria aqui no calor?',
  'Esse lugar é melhor no verão ou no inverno?',
  'Você ficaria aqui a noite inteira?',
  'Você dormiria aqui se precisasse?',
  'Você ficaria aqui sozinho de madrugada?',
  'Esse lugar dá medo?',
  'Esse lugar dá sono?',
  'Esse lugar dá fome?',
  'Esse lugar te deixa ansioso?',
  'Esse lugar te acalma?',
  'Esse lugar te dá vontade de ir embora?',
  'Você tem alguma lembrança boa de um lugar desses?',
  'Você tem alguma lembrança ruim de um lugar desses?',
  'Você contaria pra alguém que esteve aqui?',
  'Você postaria uma foto daqui?',

  // — perguntas de canalha —
  'Você indicaria esse lugar pra um amigo?',
  'Você pagaria pra nunca mais voltar aqui?',
  'Você preferiria estar aqui ou trabalhando?',
  'Esse lugar apareceria num filme de terror?',
  'Esse lugar apareceria numa novela?',
  'Esse lugar cabe na palma da mão de alguém importante?',
  'Se esse lugar sumisse amanhã, alguém sentiria falta?',
  'Você levaria alguém aqui pra impressionar?',
  'Você esconderia de alguém que veio aqui?',
  'Você conseguiria descrever esse lugar pro seu avô?',
  'Uma pessoa de cem anos atrás entenderia esse lugar?',
  'Uma criança de cinco anos gostaria daqui?',
  'Você confiaria nas pessoas daqui?',
  'Você deixaria sua mochila aqui sem olhar?',
  'Você aceitaria um copo de água de alguém aqui?',
  'Você acharia estranho ver alguém correndo aqui?',
  'Você acharia estranho ver alguém dormindo aqui?',
  'Você acharia estranho ver um cachorro aqui?',
  'Você acharia estranho ver alguém de terno aqui?',
  'Se alguém gritasse aqui, alguém viria ver?',
]
