/**
 * `CCT-31`…`CCT-33` — conteúdo estático do Cartas Contra a Turma.
 *
 * Formato próprio (e não `PacoteCompleto`): aqui um pacote traz **dois**
 * baralhos, perguntas e respostas, e não há dificuldade — o que separa os
 * pacotes é o **tom**, escolhido no lobby. Adicionar um pacote é adicionar um
 * item nesta lista; nada mais no código precisa mudar.
 */
export interface PacoteDeCartasTurma {
  id: string
  emoji: string
  nome: string
  descricao: string
  /** Total de cartas do pacote (perguntas + respostas), para o resumo do lobby. */
  quantidade: number
  jogoId: string
  /** `CCT-31` — o que a mesa está escolhendo de verdade ao marcar o pacote. */
  tom: 'leve' | 'pesado'
  /** Frases com `_____` no lugar da lacuna. */
  perguntas: string[]
  respostas: string[]
}

const RODA_DE_AMIGOS_PERGUNTAS = [
  'O segredo de uma vida longa e feliz é _____.',
  'Nunca vou perdoar meus pais por _____.',
  'O que eu jogo na mala quinze minutos antes da viagem? _____.',
  'A verdadeira razão do meu atraso foi _____.',
  'Meu superpoder completamente inútil é _____.',
  'O grupo da família só fala sobre _____.',
  'Depois de dez anos de terapia, descobri que o problema era _____.',
  'Nada estraga um churrasco como _____.',
  'Minha bio no aplicativo de encontros diz: _____.',
  'O pior de acordar cedo é _____.',
  'O que está faltando na minha vida é _____.',
  'Coloquei no currículo: _____.',
  'Meu chefe me chamou na sala pra falar sobre _____.',
  'A nova mania da molecada é _____.',
  'Não consigo dormir pensando em _____.',
  'O motivo real do trânsito de hoje foi _____.',
  'Meu plano infalível pra ficar rico envolve _____.',
  'A comida da festa acabou e sobrou só _____.',
  'A pior forma de terminar um namoro é com _____.',
  'Trouxe pro amigo secreto: _____.',
  'A primeira coisa que faço se ganhar na loteria é _____.',
  'Minha professora do fundamental nunca esqueceu _____.',
  'O que mora embaixo da minha cama? _____.',
  'A academia seria bem mais cheia se tivesse _____.',
  'Meu maior arrependimento da adolescência é _____.',
  'O que o Brasil realmente precisa é de _____.',
  'Meu pet me olha com desprezo por causa de _____.',
  'Essa reunião podia ter sido um e-mail sobre _____.',
  'Nunca deixe seu avô perto de _____.',
  'O segredo do meu bolo é _____.',
  'A pior desculpa pra faltar no trabalho é _____.',
  'O que arruinou meu domingo foi _____.',
  'Meu vizinho ficou famoso no prédio por _____.',
  'Toda vez que viajo, esqueço _____.',
  'Meus amigos pararam de me convidar por causa de _____.',
  'A propaganda jurava que curava tudo, menos _____.',
  'O que eu faria se ninguém estivesse olhando? _____.',
  'A pior lembrancinha de casamento é _____.',
  'O que eu falo pro espelho toda manhã? _____.',
  'Meu maior talento escondido é _____.',
]

const RODA_DE_AMIGOS_RESPOSTAS = [
  'Um pote de sorvete vazio no congelador',
  'A tia que fala alto no ônibus',
  'Chinelo com meia branca',
  'Reunião de condomínio',
  'Um boleto vencido',
  'O Wi-Fi do vizinho',
  'Um áudio de nove minutos',
  'Pão de queijo requentado três vezes',
  'Fila de banco na sexta-feira',
  'Grupo de família com oitenta e sete pessoas',
  'Bom dia com glitter',
  'O café frio esquecido no micro-ondas',
  'Meia sem par',
  'A chave que sumiu em 2019',
  'Uma planta que eu esqueci de regar',
  'Currículo desatualizado desde 2017',
  'Domingo às seis da tarde',
  'A segunda-feira inteira',
  'Duzentas fotos do mesmo pôr do sol',
  'Um cachorro latindo pro nada',
  'O despertador das cinco da manhã',
  'Farofa de saquinho',
  'Refrigerante sem gás',
  'Um abraço que durou tempo demais',
  'Vergonha alheia',
  'A playlist do churrasco no repeat',
  'Aquele primo que sabe tudo',
  'Uma mensagem de "podemos conversar?"',
  'Vinte reais na calça velha',
  'A calça que não fecha mais',
  'Batata frita murcha',
  'Pedido de PIX no grupo',
  'Motorista de aplicativo muito conversador',
  'Cadeira de plástico branca',
  'O ventilador que bate na parede',
  'Sofá ainda com o plástico',
  'Bolo de aniversário sem vela',
  'Karaokê às três da manhã',
  'A coreografia dos anos 2000',
  'Foto de perfil de 2013',
  'A senha que eu esqueci de novo',
  'Autenticação em duas etapas',
  'Um cabo de carregador de meio metro',
  'Bateria em 1%',
  'Print de conversa fora de contexto',
  'Uma indireta no status',
  'Vídeo com música alta no volume máximo',
  'A tampa da caneta mastigada',
  'Um adesivo que não sai da geladeira',
  'Pilha de roupa na cadeira do quarto',
  'A gaveta da bagunça',
  'Sacola de sacolas',
  'Pote de sorvete com feijão dentro',
  'Talher que só sai no Natal',
  'A toalha de mesa da vovó',
  'Um bicho de pelúcia da infância',
  'Álbum de figurinhas incompleto',
  'A tarefa de casa entregue no ônibus',
  'Redação sobre as férias',
  'Feira de ciências com vulcão de bicarbonato',
  'O quadro de aviso da escola',
  'Merenda trocada no recreio',
  'Aula de educação física na chuva',
  'Excursão de escola',
  'Um professor substituto perdido',
  'O bilhete que a mãe assinou sem ler',
  'A mochila com rodinha quebrada',
  'Café de padaria às seis da manhã',
  'Coxinha do dia anterior',
  'Suco de caixinha morno',
  'A pizza de segunda-feira',
  'Marmita esquentada no trabalho',
  'A última fatia que ninguém pega',
  'Rodízio no qual eu comi demais',
  'Molho de alho em quantidade preocupante',
  'Pipoca queimada',
  'Miojo às duas da manhã',
  'Um sanduíche montado no escuro',
  'Chá de camomila com esperança',
  'Água de torneira em copo de requeijão',
  'A colher de pau da minha mãe',
  'Um churrasco que virou reunião',
  'Cerveja quente',
  'Gelo que acabou primeiro',
  'A caixa de som do vizinho',
  'Festa junina fora de época',
  'Bingo de igreja',
  'Amigo secreto com regra confusa',
  'A pessoa que tira foto de tudo',
  'Aquele que chega quando a festa acaba',
  'Dança da cadeira levada muito a sério',
  'Uma cantada de 1998',
  'Terceiro encontro com silêncio constrangedor',
  'Meu tipo de humor',
  'Autoestima em dia de foto',
  'A minha capacidade de piorar as coisas',
  'Otimismo sem base nenhuma',
  'Um plano feito às pressas',
  'Confiança absoluta em algo errado',
  'Motivação de segunda que morre na terça',
  'Um caderno novo comprado com esperança',
  'Meta de academia em janeiro',
  'Curso online que eu nunca comecei',
  'Aquele livro na terceira página desde 2020',
  'Fone com um lado só funcionando',
  'Notificação às três da manhã',
  'O algoritmo me entendendo bem demais',
  'Carrinho de compras cheio e não finalizado',
  'Frete grátis a dez reais de distância',
  'Cupom que expirou ontem',
  'Entrega marcada como concluída sem chegar',
  'Fila do caixa que eu escolhi errado',
  'Carrinho de supermercado com roda torta',
  'Promoção que era só o preço antigo',
  'A vaga de estacionamento perfeita',
  'Pombo com intenções claras',
  'Um gato que derruba tudo de propósito',
  'Formiga na cozinha às onze da noite',
  'Barata voadora',
  'O cachorro do vizinho me julgando',
  'Papagaio que fala mais que devia',
  'Peixe de aquário com nome de pessoa',
  'Uma galinha muito confiante',
]

const SEM_FILTRO_PERGUNTAS = [
  'O que eu não conto pra minha mãe? _____.',
  'A verdadeira causa do fim do meu último relacionamento foi _____.',
  'Meu terapeuta desistiu de mim quando eu falei de _____.',
  'O que me faz acordar às quatro da manhã suando? _____.',
  'No meu velório, quero que toquem _____.',
  'Meu segredo mais constrangedor é _____.',
  'O que rolou na festa que ninguém deve comentar? _____.',
  'A pior coisa que já fiz bêbado foi _____.',
  'Meu histórico de navegação é 90% _____.',
  'O motivo real do meu ex ter bloqueado meu número é _____.',
  'O que eu penso durante a reunião de segunda? _____.',
  'A frase que encerra qualquer amizade é _____.',
  'Meu maior medo é morrer por causa de _____.',
  'A única coisa que ainda me segura na vida é _____.',
  'Fui demitido por causa de _____.',
  'O que eu fingi entender a vida inteira? _____.',
  'Meu pior encontro terminou com _____.',
  'A pior coisa de morar sozinho é _____.',
  'O que eu escondo quando chega visita? _____.',
  'O que eu levaria pro apocalipse? _____.',
  'A parte mais deprimente de ser adulto é _____.',
  'O que ninguém avisa sobre os trinta? _____.',
  'Meu plano B se tudo der errado é _____.',
  'A coisa mais cara que eu comprei arrependido foi _____.',
  'O que eu diria na minha última mensagem? _____.',
  'A herança que eu vou deixar é _____.',
  'Meu boleto favorito é o de _____.',
  'O que arruinou meu Natal em família? _____.',
  'Meu vizinho ouviu, através da parede, _____.',
  'O que eu faço quando ninguém está em casa? _____.',
  'A tatuagem que eu me arrependo é de _____.',
  'A pior dor que eu já senti foi _____.',
  'O que eu procuro às três da manhã? _____.',
  'A verdadeira razão de eu não atender ligação é _____.',
  'O que eu prometi e nunca cumpri? _____.',
  'Meu limite de vergonha na cara é _____.',
  'O que me faz sair de um grupo sem avisar? _____.',
  'A pior notícia pra receber num domingo é _____.',
  'Meu currículo mente sobre _____.',
  'O apocalipse vai começar por causa de _____.',
]

const SEM_FILTRO_RESPOSTAS = [
  'Minha dívida no cartão',
  'O extrato da conta no dia 20',
  'Cheque especial',
  'O boleto do dentista',
  'Financiamento de trinta anos',
  'A minha declaração de imposto de renda',
  'Aquele empréstimo que eu peguei pra nada',
  'Salário que acaba no dia 5',
  'A crise dos trinta chegando adiantada',
  'Terapia que eu não posso pagar',
  'Ansiedade em nível competitivo',
  'Meu cérebro às quatro da manhã',
  'Uma crise existencial no chuveiro',
  'O silêncio depois que a festa acaba',
  'Chorar no carro no estacionamento',
  'Rir em hora errada',
  'Minha capacidade de piorar tudo',
  'Autossabotagem profissional',
  'A vontade de sumir por seis meses',
  'Ligar pro ex às duas da manhã',
  'Stalkear o perfil de alguém até 2016',
  'Curtir foto de 2014 sem querer',
  'Mandar mensagem pro chat errado',
  'Print encaminhado pra pessoa errada',
  'Áudio gravado sem querer',
  'Aquela mensagem que eu apaguei tarde demais',
  'Bloqueio recíproco',
  'Um término por mensagem',
  'Uma indireta muito direta',
  'Ciúme sem fundamento nenhum',
  'A senha do streaming que ainda é do ex',
  'Um encontro que virou terapia de graça',
  'Ficar com o amigo do amigo',
  'Beijo com gosto de cachaça',
  'Ressaca de três dias',
  'A cachaça do tio',
  'Cerveja quente às oito da manhã',
  'Vomitar no Uber',
  'Um karaokê com escolhas questionáveis',
  'Dançar sozinho na pista vazia',
  'A tequila que me convenceu',
  'Ligar pro chefe bêbado',
  'Dormir no sofá de um desconhecido',
  'Acordar sem saber onde estou',
  'Perder o celular pela terceira vez',
  'Um boletim de ocorrência',
  'Multa por excesso de confiança',
  'O guarda que não achou graça',
  'Explicar isso pra polícia',
  'Uma discussão no grupo do condomínio',
  'Briga de família no Natal',
  'A pergunta "e o casamento?"',
  'Tia perguntando do meu salário',
  'Meu primo bem-sucedido',
  'A comparação com o filho da vizinha',
  'Um sermão de duas horas',
  'A cara de decepção da minha mãe',
  'Meu pai descobrindo a verdade',
  'O tio do churrasco falando de política',
  'Uma teoria da conspiração no almoço',
  'Corrente de WhatsApp',
  'Fake news da tia',
  'O grupo da família às seis da manhã',
  'Um áudio de dezoito minutos',
  'Alguém falando no viva-voz em público',
  'A pessoa que responde "kkk" e some',
  'Visualizado e não respondido',
  'Digitando… por quinze minutos',
  'Um "boa noite" às três da manhã',
  'Chamada de vídeo sem aviso',
  'Meu histórico de navegação',
  'A aba anônima',
  'Recomendação de algoritmo constrangedora',
  'Assinar coisa que eu não uso',
  'Renovação automática',
  'Sete assinaturas de streaming',
  'Comprar às três da manhã',
  'Um carrinho abandonado com culpa',
  'Aquela compra por impulso',
  'A esteira que virou cabide',
  'Academia paga e nunca visitada',
  'Meta de ano novo esquecida em fevereiro',
  'Dieta que durou um almoço',
  'Segunda-feira, sempre segunda-feira',
  'A reunião que podia ser um e-mail',
  'Home office de pijama',
  'Câmera desligada por um bom motivo',
  'Fingir que a internet caiu',
  'Trabalhar doente',
  'Pedir demissão em pensamento',
  'O e-mail com "conforme alinhado"',
  'Cobrança do chefe às sete da noite',
  'Feedback que não era feedback',
  'Promoção que virou mais trabalho',
  'Currículo com meia verdade',
  'A entrevista em que eu menti',
  'Dinâmica de grupo',
  'Perguntar "onde você se vê em cinco anos?"',
  'Meu maior defeito ser "perfeccionismo"',
  'Um LinkedIn muito otimista',
  'Insônia crônica',
  'Ranger os dentes dormindo',
  'A dor nas costas aos vinte e oito',
  'O joelho que estala',
  'Cabelo branco na barba',
  'A entrada capilar avançando',
  'Cansaço que dormir não resolve',
  'Enxaqueca de dois dias',
  'O exame que eu adiei por dois anos',
  'Consulta com o proctologista',
  'A anestesia falando por mim',
  'Meu plano de saúde negando tudo',
  'A fila do SUS',
  'Um diagnóstico pesquisado na internet',
  'Automedicação corajosa',
  'Sobreviver a mim mesmo',
  'A morte, mas com humor',
  'Meu testamento escrito no guardanapo',
  'Um caixão financiado',
  'Cremação com playlist',
  'A herança em boletos',
  'Ninguém no meu velório',
]

/** `CCT-31`, `CCT-33` — os pacotes disponíveis, separados por tom. */
export const CARTAS_TURMA: PacoteDeCartasTurma[] = [
  {
    id: 'cartas-roda-de-amigos',
    emoji: '🍿',
    nome: 'Roda de Amigos',
    descricao: 'Dá pra jogar com a família na sala. Tom leve.',
    quantidade: RODA_DE_AMIGOS_PERGUNTAS.length + RODA_DE_AMIGOS_RESPOSTAS.length,
    jogoId: 'cartas-contra-a-turma',
    tom: 'leve',
    perguntas: RODA_DE_AMIGOS_PERGUNTAS,
    respostas: RODA_DE_AMIGOS_RESPOSTAS,
  },
  {
    id: 'cartas-sem-filtro',
    emoji: '🚬',
    nome: 'Sem Filtro',
    descricao: 'Dívida, ressaca e crise existencial. Tom pesado, mesa adulta.',
    quantidade: SEM_FILTRO_PERGUNTAS.length + SEM_FILTRO_RESPOSTAS.length,
    jogoId: 'cartas-contra-a-turma',
    tom: 'pesado',
    perguntas: SEM_FILTRO_PERGUNTAS,
    respostas: SEM_FILTRO_RESPOSTAS,
  },
]
