/**
 * `CCT-31`…`CCT-33` — conteúdo estático do Cartas Contra a Turma.
 *
 * Formato próprio (e não `PacoteCompleto`): aqui um pacote traz **dois**
 * baralhos, perguntas e respostas, e não há dificuldade — o que separa os
 * pacotes é o **tom**, escolhido no lobby. Adicionar um pacote é adicionar um
 * item nesta lista; nada mais no código precisa mudar.
 *
 * ## O tom é um contrato com a mesa
 *
 * `leve` dá pra jogar na sala com a família. `pesado` e `toxico` não: ali a
 * carta é sobre sexo ruim, morte, dinheiro e o que a pessoa faria se ninguém
 * visse. **Carta morna nesses pacotes é carta ruim** — se a resposta não faz
 * ninguém negar nada, o juiz não tem do que rir.
 *
 * O limite não é a intensidade, é o alvo: a carta fala de **escolha e do que
 * acontece com um corpo qualquer**, nunca de quem a pessoa é sem ter escolhido
 * (aparência, deficiência, origem, sexualidade, fé de ninguém). Também não
 * entra nome de gente real, nem nada envolvendo criança.
 */
export interface PacoteDeCartasTurma {
  id: string
  emoji: string
  nome: string
  descricao: string
  /**
   * Crédito e licença do conteúdo, quando ele não é nosso. Exigência da
   * licença, não enfeite: um pacote adaptado de obra alheia **precisa** dizer
   * de onde veio onde a mesa escolhe (ver `CONTEUDO.md`).
   */
  creditos?: string
  /** Total de cartas do pacote (perguntas + respostas), para o resumo do lobby. */
  quantidade: number
  jogoId: string
  /** `CCT-31` — o que a mesa está escolhendo de verdade ao marcar o pacote. */
  tom: 'leve' | 'pesado' | 'toxico'
  /** Frases com `_____` no lugar da lacuna. */
  perguntas: string[]
  respostas: string[]
}

const RODA_DE_AMIGOS_PERGUNTAS = [
  'O segredo de uma vida longa e feliz é _____.',
  'Nunca vou perdoar meus pais por _____.',
  'O que eu jogo na mala quinze minutos antes da viagem? _____.',
  'A verdadeira razão do meu atraso foi _____.',
  'Meu superpoder completamente inútil é _____.',
  'O grupo da família só fala sobre _____.',
  'Depois de dez anos de terapia, descobri que o problema era _____.',
  'Nada estraga um churrasco como _____.',
  'Minha bio no aplicativo de encontros diz: _____.',
  'O pior de acordar cedo é _____.',
  'O que está faltando na minha vida é _____.',
  'Coloquei no currículo: _____.',
  'Meu chefe me chamou na sala pra falar sobre _____.',
  'A nova mania da molecada é _____.',
  'Não consigo dormir pensando em _____.',
  'O motivo real do trânsito de hoje foi _____.',
  'Meu plano infalível pra ficar rico envolve _____.',
  'A comida da festa acabou e sobrou só _____.',
  'A pior forma de terminar um namoro é com _____.',
  'Trouxe pro amigo secreto: _____.',
  'A primeira coisa que faço se ganhar na loteria é _____.',
  'Minha professora do fundamental nunca esqueceu _____.',
  'O que mora embaixo da minha cama? _____.',
  'A academia seria bem mais cheia se tivesse _____.',
  'Meu maior arrependimento da adolescência é _____.',
  'O que o Brasil realmente precisa é de _____.',
  'Meu pet me olha com desprezo por causa de _____.',
  'Essa reunião podia ter sido um e-mail sobre _____.',
  'Nunca deixe seu avô perto de _____.',
  'O segredo do meu bolo é _____.',
  'A pior desculpa pra faltar no trabalho é _____.',
  'O que arruinou meu domingo foi _____.',
  'Meu vizinho ficou famoso no prédio por _____.',
  'Toda vez que viajo, esqueço _____.',
  'Meus amigos pararam de me convidar por causa de _____.',
  'A propaganda jurava que curava tudo, menos _____.',
  'O que eu faria se ninguém estivesse olhando? _____.',
  'A pior lembrancinha de casamento é _____.',
  'O que eu falo pro espelho toda manhã? _____.',
  'Meu maior talento escondido é _____.',
]

const RODA_DE_AMIGOS_RESPOSTAS = [
  'Um pote de sorvete vazio no congelador',
  'A tia que fala alto no ônibus',
  'Chinelo com meia branca',
  'Reunião de condomínio',
  'Um boleto vencido',
  'O Wi-Fi do vizinho',
  'Um áudio de nove minutos',
  'Pão de queijo requentado três vezes',
  'Fila de banco na sexta-feira',
  'Grupo de família com oitenta e sete pessoas',
  'Bom dia com glitter',
  'O café frio esquecido no micro-ondas',
  'Meia sem par',
  'A chave que sumiu em 2019',
  'Uma planta que eu esqueci de regar',
  'Currículo desatualizado desde 2017',
  'Domingo às seis da tarde',
  'A segunda-feira inteira',
  'Duzentas fotos do mesmo pôr do sol',
  'Um cachorro latindo pro nada',
  'O despertador das cinco da manhã',
  'Farofa de saquinho',
  'Refrigerante sem gás',
  'Um abraço que durou tempo demais',
  'Vergonha alheia',
  'A playlist do churrasco no repeat',
  'Aquele primo que sabe tudo',
  'Uma mensagem de "podemos conversar?"',
  'Vinte reais na calça velha',
  'A calça que não fecha mais',
  'Batata frita murcha',
  'Pedido de PIX no grupo',
  'Motorista de aplicativo muito conversador',
  'Cadeira de plástico branca',
  'O ventilador que bate na parede',
  'Sofá ainda com o plástico',
  'Bolo de aniversário sem vela',
  'Karaokê às três da manhã',
  'A coreografia dos anos 2000',
  'Foto de perfil de 2013',
  'A senha que eu esqueci de novo',
  'Autenticação em duas etapas',
  'Um cabo de carregador de meio metro',
  'Bateria em 1%',
  'Print de conversa fora de contexto',
  'Uma indireta no status',
  'Vídeo com música alta no volume máximo',
  'A tampa da caneta mastigada',
  'Um adesivo que não sai da geladeira',
  'Pilha de roupa na cadeira do quarto',
  'A gaveta da bagunça',
  'Sacola de sacolas',
  'Pote de sorvete com feijão dentro',
  'Talher que só sai no Natal',
  'A toalha de mesa da vovó',
  'Um bicho de pelúcia da infância',
  'Álbum de figurinhas incompleto',
  'A tarefa de casa entregue no ônibus',
  'Redação sobre as férias',
  'Feira de ciências com vulcão de bicarbonato',
  'O quadro de aviso da escola',
  'Merenda trocada no recreio',
  'Aula de educação física na chuva',
  'Excursão de escola',
  'Um professor substituto perdido',
  'O bilhete que a mãe assinou sem ler',
  'A mochila com rodinha quebrada',
  'Café de padaria às seis da manhã',
  'Coxinha do dia anterior',
  'Suco de caixinha morno',
  'A pizza de segunda-feira',
  'Marmita esquentada no trabalho',
  'A última fatia que ninguém pega',
  'Rodízio no qual eu comi demais',
  'Molho de alho em quantidade preocupante',
  'Pipoca queimada',
  'Miojo às duas da manhã',
  'Um sanduíche montado no escuro',
  'Chá de camomila com esperança',
  'Água de torneira em copo de requeijão',
  'A colher de pau da minha mãe',
  'Um churrasco que virou reunião',
  'Cerveja quente',
  'Gelo que acabou primeiro',
  'A caixa de som do vizinho',
  'Festa junina fora de época',
  'Bingo de igreja',
  'Amigo secreto com regra confusa',
  'A pessoa que tira foto de tudo',
  'Aquele que chega quando a festa acaba',
  'Dança da cadeira levada muito a sério',
  'Uma cantada de 1998',
  'Terceiro encontro com silêncio constrangedor',
  'Meu tipo de humor',
  'Autoestima em dia de foto',
  'A minha capacidade de piorar as coisas',
  'Otimismo sem base nenhuma',
  'Um plano feito às pressas',
  'Confiança absoluta em algo errado',
  'Motivação de segunda que morre na terça',
  'Um caderno novo comprado com esperança',
  'Meta de academia em janeiro',
  'Curso online que eu nunca comecei',
  'Aquele livro na terceira página desde 2020',
  'Fone com um lado só funcionando',
  'Notificação às três da manhã',
  'O algoritmo me entendendo bem demais',
  'Carrinho de compras cheio e não finalizado',
  'Frete grátis a dez reais de distância',
  'Cupom que expirou ontem',
  'Entrega marcada como concluída sem chegar',
  'Fila do caixa que eu escolhi errado',
  'Carrinho de supermercado com roda torta',
  'Promoção que era só o preço antigo',
  'A vaga de estacionamento perfeita',
  'Pombo com intenções claras',
  'Um gato que derruba tudo de propósito',
  'Formiga na cozinha às onze da noite',
  'Barata voadora',
  'O cachorro do vizinho me julgando',
  'Papagaio que fala mais que devia',
  'Peixe de aquário com nome de pessoa',
  'Uma galinha muito confiante',
]

const SEM_FILTRO_PERGUNTAS = [
  'O que eu não conto pra minha mãe? _____.',
  'A verdadeira causa do fim do meu último relacionamento foi _____.',
  'Meu terapeuta desistiu de mim quando eu falei de _____.',
  'O que me faz acordar às quatro da manhã suando? _____.',
  'No meu velório, quero que toquem _____.',
  'Meu segredo mais constrangedor é _____.',
  'O que rolou na festa que ninguém deve comentar? _____.',
  'A pior coisa que já fiz bêbado foi _____.',
  'Meu histórico de navegação é 90% _____.',
  'O motivo real do meu ex ter bloqueado meu número é _____.',
  'O que eu penso durante a reunião de segunda? _____.',
  'A frase que encerra qualquer amizade é _____.',
  'Meu maior medo é morrer por causa de _____.',
  'A única coisa que ainda me segura na vida é _____.',
  'Fui demitido por causa de _____.',
  'O que eu fingi entender a vida inteira? _____.',
  'Meu pior encontro terminou com _____.',
  'A pior coisa de morar sozinho é _____.',
  'O que eu escondo quando chega visita? _____.',
  'O que eu levaria pro apocalipse? _____.',
  'A parte mais deprimente de ser adulto é _____.',
  'O que ninguém avisa sobre os trinta? _____.',
  'Meu plano B se tudo der errado é _____.',
  'A coisa mais cara que eu comprei arrependido foi _____.',
  'O que eu diria na minha última mensagem? _____.',
  'A herança que eu vou deixar é _____.',
  'Meu boleto favorito é o de _____.',
  'O que arruinou meu Natal em família? _____.',
  'Meu vizinho ouviu, através da parede, _____.',
  'O que eu faço quando ninguém está em casa? _____.',
  'A tatuagem que eu me arrependo é de _____.',
  'A pior dor que eu já senti foi _____.',
  'O que eu procuro às três da manhã? _____.',
  'A verdadeira razão de eu não atender ligação é _____.',
  'O que eu prometi e nunca cumpri? _____.',
  'Meu limite de vergonha na cara é _____.',
  'O que me faz sair de um grupo sem avisar? _____.',
  'A pior notícia pra receber num domingo é _____.',
  'Meu currículo mente sobre _____.',
  'O apocalipse vai começar por causa de _____.',
]

const SEM_FILTRO_RESPOSTAS = [
  'Minha dívida no cartão',
  'O extrato da conta no dia 20',
  'Cheque especial',
  'O boleto do dentista',
  'Financiamento de trinta anos',
  'A minha declaração de imposto de renda',
  'Aquele empréstimo que eu peguei pra nada',
  'Salário que acaba no dia 5',
  'A crise dos trinta chegando adiantada',
  'Terapia que eu não posso pagar',
  'Ansiedade em nível competitivo',
  'Meu cérebro às quatro da manhã',
  'Uma crise existencial no chuveiro',
  'O silêncio depois que a festa acaba',
  'Chorar no carro no estacionamento',
  'Rir em hora errada',
  'Minha capacidade de piorar tudo',
  'Autossabotagem profissional',
  'A vontade de sumir por seis meses',
  'Ligar pro ex às duas da manhã',
  'Stalkear o perfil de alguém até 2016',
  'Curtir foto de 2014 sem querer',
  'Mandar mensagem pro chat errado',
  'Print encaminhado pra pessoa errada',
  'Áudio gravado sem querer',
  'Aquela mensagem que eu apaguei tarde demais',
  'Bloqueio recíproco',
  'Um término por mensagem',
  'Uma indireta muito direta',
  'Ciúme sem fundamento nenhum',
  'A senha do streaming que ainda é do ex',
  'Um encontro que virou terapia de graça',
  'Ficar com o amigo do amigo',
  'Beijo com gosto de cachaça',
  'Ressaca de três dias',
  'A cachaça do tio',
  'Cerveja quente às oito da manhã',
  'Vomitar no Uber',
  'Um karaokê com escolhas questionáveis',
  'Dançar sozinho na pista vazia',
  'A tequila que me convenceu',
  'Ligar pro chefe bêbado',
  'Dormir no sofá de um desconhecido',
  'Acordar sem saber onde estou',
  'Perder o celular pela terceira vez',
  'Um boletim de ocorrência',
  'Multa por excesso de confiança',
  'O guarda que não achou graça',
  'Explicar isso pra polícia',
  'Uma discussão no grupo do condomínio',
  'Briga de família no Natal',
  'A pergunta "e o casamento?"',
  'Tia perguntando do meu salário',
  'Meu primo bem-sucedido',
  'A comparação com o filho da vizinha',
  'Um sermão de duas horas',
  'A cara de decepção da minha mãe',
  'Meu pai descobrindo a verdade',
  'O tio do churrasco falando de política',
  'Uma teoria da conspiração no almoço',
  'Corrente de WhatsApp',
  'Fake news da tia',
  'O grupo da família às seis da manhã',
  'Um áudio de dezoito minutos',
  'Alguém falando no viva-voz em público',
  'A pessoa que responde "kkk" e some',
  'Visualizado e não respondido',
  'Digitando… por quinze minutos',
  'Um "boa noite" às três da manhã',
  'Chamada de vídeo sem aviso',
  'Meu histórico de navegação',
  'A aba anônima',
  'Recomendação de algoritmo constrangedora',
  'Assinar coisa que eu não uso',
  'Renovação automática',
  'Sete assinaturas de streaming',
  'Comprar às três da manhã',
  'Um carrinho abandonado com culpa',
  'Aquela compra por impulso',
  'A esteira que virou cabide',
  'Academia paga e nunca visitada',
  'Meta de ano novo esquecida em fevereiro',
  'Dieta que durou um almoço',
  'Segunda-feira, sempre segunda-feira',
  'A reunião que podia ser um e-mail',
  'Home office de pijama',
  'Câmera desligada por um bom motivo',
  'Fingir que a internet caiu',
  'Trabalhar doente',
  'Pedir demissão em pensamento',
  'O e-mail com "conforme alinhado"',
  'Cobrança do chefe às sete da noite',
  'Feedback que não era feedback',
  'Promoção que virou mais trabalho',
  'Currículo com meia verdade',
  'A entrevista em que eu menti',
  'Dinâmica de grupo',
  'Perguntar "onde você se vê em cinco anos?"',
  'Meu maior defeito ser "perfeccionismo"',
  'Um LinkedIn muito otimista',
  'Insônia crônica',
  'Ranger os dentes dormindo',
  'A dor nas costas aos vinte e oito',
  'O joelho que estala',
  'Cabelo branco na barba',
  'A entrada capilar avançando',
  'Cansaço que dormir não resolve',
  'Enxaqueca de dois dias',
  'O exame que eu adiei por dois anos',
  'Consulta com o proctologista',
  'A anestesia falando por mim',
  'Meu plano de saúde negando tudo',
  'A fila do SUS',
  'Um diagnóstico pesquisado na internet',
  'Automedicação corajosa',
  'Sobreviver a mim mesmo',
  'A morte, mas com humor',
  'Meu testamento escrito no guardanapo',
  'Um caixão financiado',
  'Cremação com playlist',
  'A herança em boletos',
  'Ninguém no meu velório',
]


const TOXICO_PERGUNTAS = [
  'O que tá na minha aba anônima? _____.',
  'Meu fetiche mais constrangedor é _____.',
  'O que acabou com o meu casamento? _____.',
  'O que a mesa nunca vai me deixar esquecer? _____.',
  'Meu ex ainda tem pesadelo com _____.',
  'O que eu não conto nem no confessionário? _____.',
  'Deus ainda vai me cobrar por _____.',
  'O que rolou naquele motel? _____.',
  'A pior coisa pra dizer na hora H é _____.',
  'O que estraga um nude? _____.',
  'Meu terapeuta largou o caso depois de _____.',
  'O que eu fiz bêbado e nunca assumi? _____.',
  'A pior forma de morrer é _____.',
  'No meu velório vão ficar comentando sobre _____.',
  'O que meus pais acharam no meu quarto? _____.',
  'O que a polícia achou no meu carro? _____.',
  'Eu venderia a minha dignidade por _____.',
  'O que eu mandei sem querer no grupo da família? _____.',
  'O que tem escrito no meu prontuário? _____.',
  'A pior coisa pra ouvir do médico é _____.',
  'O que arruinou o Natal? _____.',
  'O que meu vizinho ouve pela parede? _____.',
  'Meu maior arrependimento sexual é _____.',
  'A pior forma de descobrir uma traição é _____.',
  'O que eu falo dormindo? _____.',
  'O que me fez ser cancelado? _____.',
  'Eu perdi o emprego por causa de _____.',
  'O que eu faria por mil reais? _____.',
  'A pior coisa pra ouvir depois do sexo é _____.',
  'O que a minha mãe descobriu e fingiu que não viu? _____.',
  'O que eu procuro no aplicativo às três da manhã? _____.',
  'A primeira coisa que a minha alma vai responder no julgamento final é _____.',
  'O que eu escondi debaixo da cama antes da visita chegar? _____.',
  'Do que eu tenho vergonha e ainda assim faço toda semana? _____.',
  'A pior coisa de se descobrir no meio da transa é _____.',
  'O que eu paguei e nunca contei pra ninguém? _____.',
  'O que me faz chorar no chuveiro? _____.',
  'O que eu levaria no bolso pro inferno? _____.',
  'Qual é a minha última vontade? _____.',
  'A pior coisa de se receber de presente do amigo secreto é _____.',
]

const TOXICO_RESPOSTAS = [
  'Gozar em quarenta segundos',
  'Chamar pelo nome do ex na hora H',
  'Brochar no melhor momento',
  'Fingir orgasmo com convicção de ator',
  'Um vídeo caseiro que ainda existe em algum servidor',
  'Uma punheta triste de domingo à tarde',
  'Cinquenta minutos de preliminares e nada',
  'Sexo de reconciliação com quem eu odeio',
  'Um fetiche que ninguém aqui ia entender',
  'Pornô alemão',
  'Match com o próprio primo',
  'A chefe no aplicativo de pegação',
  'Piercing no mamilo',
  'O clitóris, aquele desconhecido',
  'Nudes vazados no grupo do trabalho',
  'Camisinha estourada e silêncio',
  'Um chupão no dia da reunião de família',
  'Transar ouvindo os pais dela no corredor',
  'Um brinquedinho com a pilha fraca',
  'Sexo por pena',
  'Um "tá acordada?" às três da manhã',
  'A luz acesa e sem filtro nenhum',
  'Pedir pra repetir e ouvir não',
  'Cinco anos de seca',
  'Descobrir a traição pelo Instagram',
  'O ex que ainda tem a chave de casa',
  'Um trisal mal explicado',
  'Beijar de língua com gosto de vômito',
  'Pelo encravado em lugar de difícil explicação',
  'Levar um fora no meio do ato',
  'A morte térmica do universo',
  'Morrer no banheiro do trabalho',
  'Um caixão financiado em doze vezes',
  'Meus pais mortos',
  'Um moinho cheio de cadáveres',
  'O silêncio de uma UTI às quatro da manhã',
  'Enterrar o cachorro no jardim de madrugada',
  'A herança que virou dívida',
  'Um obituário com erro de digitação',
  'Cremação sem ninguém chorando',
  'Missa de sétimo dia com quatro pessoas',
  'O resultado da biópsia',
  'Descobrir que era hereditário',
  'A conta do hospital',
  'Uma reza que não funcionou',
  'Culpa católica de trinta e sete anos',
  'O pastor pedindo mais dízimo',
  'Jesus voltando na hora mais inconveniente',
  'O arrebatamento pegando todo mundo de calça arriada',
  'Vender a alma por bem menos do que ela vale',
  'Diarreia em banheiro alheio',
  'Cagar e descobrir que não tem papel',
  'Vomitar no colo de alguém',
  'Um arroto com gosto de ontem',
  'Menstruar na cama dos outros',
  'Peidar e culpar o cachorro',
  'Suor frio de ressaca de três dias',
  'Um dente que caiu sozinho',
  'Acordar num lençol que não é mais meu',
  'Mijar na piscina e olhar na cara de todo mundo',
  'Bala de procedência duvidosa',
  'Cheirar farinha achando que era outra coisa',
  'Remédio tarja preta com cerveja',
  'Vodka com energético às oito da manhã',
  'Cachaça de garrafa sem rótulo',
  'Apagar antes da meia-noite e acordar em outro bairro',
  'Ligar pro ex às quatro da manhã',
  'Um discurso de bêbado sobre política',
  'Dirigir bêbado com todo mundo dentro do carro',
  'Perder o celular, a carteira e a vergonha na mesma noite',
  'Bater no carro do vizinho e ir embora',
  'Deixar o amigo ser preso no meu lugar',
  'Agiota batendo na porta às sete da manhã',
  'Um sequestro relâmpago em dia de pagamento',
  'Sumir com a vaquinha do churrasco',
  'Denunciar o colega pra ficar bem com o chefe',
  'Trair e culpar a bebida',
  'Rir da desgraça alheia na frente de todo mundo',
  'Não dar a mínima pro resto do mundo',
  'Bloquear a família inteira no Natal',
  'Pegar dinheiro da bolsa da mãe',
  'Um golpe aplicado nos próprios amigos',
  'Fingir luto pra faltar no trabalho',
  'Roubar o cachorro de um desconhecido',
  'Vender o rim por um carro usado',
  'Chorar no banheiro do trabalho',
  'Fazer xixi na garrafa pra bater a meta',
  'Câmera ligada sem calça',
  'Mandar áudio de dez minutos pro chefe errado',
  'Curtir foto de dois mil e treze da chefe',
  'Dormir na reunião com o microfone aberto',
  'Pedir demissão por áudio às duas da manhã',
  'Um print de conversa vazado no grupo grande',
  'Story postado no perfil errado',
  'Histórico de busca aberto na TV da sala',
  'Um tweet de dois mil e onze',
  'Um perfil secreto descoberto pela irmã',
  'Comentar besteira na foto errada',
  'Tio bêbado tomando o microfone',
  'Sogra chegando sem avisar e ficando dez dias',
  'A pergunta "e o casamento?" na quinta taça',
  'Batizado terminando em briga generalizada',
  'Chorar na frente do crush por bobagem',
  'Um discurso de casamento que ninguém pediu',
  'Karaokê sem noção nenhuma de tom',
  'Um cavalo minúsculo',
  'Um policial que também é cachorro',
  'Bater palma quando o avião pousa',
  'Um homem de meia-idade de patins',
  'Uma barata voando na direção da minha cara',
  'Um rato do tamanho de um gato no armário',
  'A minha vida inteira em um único boleto',
  'Terapia que eu claramente não posso pagar',
  'Um ataque de pânico no meio do rolê',
  'O meu cérebro às quatro da manhã',
  'A voz da minha mãe na minha cabeça',
  'Uma tatuagem feita numa aposta',
  'Voltar a morar com os pais aos trinta e cinco',
  'Trabalhar de graça em nome da experiência',
  'Um pix de dez reais cobrado no dia seguinte',
]

const CLASSICO_PERGUNTAS = [
  'Que cheiro é esse? _____.',
  'Guerra! Pra que serve? _____.',
  'O que melhora com a idade? _____.',
  'Do que tem de sobra no céu? _____.',
  'A ciência nunca vai explicar _____.',
  'Quem controla _____ controla o mundo.',
  'Quando eu for presidente, vou criar o Ministério de _____.',
  'Em vez de carvão, o Papai Noel agora deixa pras crianças ruins _____.',
  'Antes de te matar, agente, preciso te mostrar _____.',
  'No meu próximo truque, vou tirar _____ da cartola.',
  'Daqui a mil anos, quando o dinheiro for lembrança, a moeda vai ser _____.',
  'Um jantar à luz de velas fica incompleto sem _____.',
  '_____. É assim que eu quero morrer.',
  'Eu bebo pra esquecer _____.',
  'Desculpe, professora, não fiz o trabalho por causa de _____.',
  'O passeio da escola foi arruinado por _____.',
  'Estreia no teatro: _____, o musical.',
  'A CBF baniu _____ por vantagem indevida.',
  'A ANAC proibiu _____ a bordo.',
  'O que nunca falha pra animar a festa? _____.',
  'O que eu vou largar na Quaresma? _____.',
  'Estudos mostram que ratos de laboratório resolvem labirintos 50% mais rápido depois de _____.',
  'Antropólogos acabam de achar uma tribo que venera _____.',
  'É uma pena que a molecada de hoje esteja envolvida com _____.',
  'O que a vovó acharia perturbador e ao mesmo tempo adorável? _____.',
  'O novo reality junta oito famosos decadentes numa casa com _____.',
  'Meu antidepressivo é _____.',
  'Qual é a nova dieta da moda? _____.',
  'Por que eu tô grudento? _____.',
  'Eu tenho noventa e nove problemas, e _____ não é um deles.',
  'O que não pode faltar na cesta de Natal da firma? _____.',
  'O que eu não quero achar dentro do meu yakisoba? _____.',
  'O que eu trouxe escondido do Paraguai? _____.',
  'Assim acaba o mundo: não com um estrondo, mas com _____.',
  'O presente que a gente dá e nunca acaba: _____.',
  'Qual é o meu superpoder secreto? _____.',
  'Na infância, o artista pintou centenas de quadros de _____.',
  'O próximo livro da saga: A Câmara de _____.',
  'Como eu tô mantendo meu relacionamento? _____.',
  'Beleza! Quem quer jogar _____?',
  'O que o terapeuta me proibiu de fazer? _____.',
  'O que tem no fundo da caixa que ninguém abre? _____.',
]

const CLASSICO_RESPOSTAS = [
  'Filhotinhos de cachorro',
  'Estar pegando fogo',
  'Um moinho de vento cheio de gente morta',
  'Uma sacola de feijões mágicos',
  'A vovó',
  'Carne de gente',
  'Tensão sexual insuportável',
  'Explosões',
  'Uma coreografia de jazz com muita energia',
  'Um desastre absoluto',
  'Comer o próprio braço',
  'Piercing genital',
  'Disfunção erétil',
  'Uma punheta desanimada',
  'Escolhas ruins de vida',
  'Ficar com tanta raiva que dá tesão',
  'Silêncio constrangedor',
  'Pornografia de masmorra alemã',
  'Um senhor de meia-idade andando de patins',
  'O arrebatamento',
  'A minha alma',
  'Fazer a coisa certa',
  'Uma lobotomia com picador de gelo',
  'O coração de uma criança',
  'Não dar a mínima pra fome no mundo',
  'Ficar bêbado com enxaguante bucal',
  'Um cavalinho muito pequeno',
  'Necrofilia',
  'Pelado da cintura pra cima e pra baixo',
  'Boca suja',
  'O gosto do leite materno',
  'Repressão',
  'Uma festa só de homem',
  'A morte inevitável do universo',
  'Dívida que não fecha nunca',
  'Uma vida inteira de tristeza',
  'Injeção de hormônio',
  'Sentimentos',
  'Um cachorro fardado com distintivo e tudo',
  'Roubar túmulo',
  'Uma cagada inesquecível',
  'Abelhas',
  'Bilhões de dólares',
  'Um genocídio bem organizado',
  'A menstruação',
  'Sacrifício humano',
  'Uma bela salada',
  'Vinte quilos de macarrão',
  'Cair de cara no chão',
  'Um choro daqueles no chuveiro',
  'Escravidão do trabalho',
  'A mão invisível do mercado',
  'Um crucifixo de plástico brilhando no escuro',
  'Um padre de folga',
  'Deus, se ele existir',
  'Aquele amigo que ninguém convidou',
  'Um tapa na cara com luva de pelica',
  'Sexo triste',
  'Um bebê chorando num avião',
  'Todo mundo olhando',
  'Meu pai sem camisa',
  'Sufoco financeiro',
  'A vergonha na cara que eu não tenho',
  'Um pote de manteiga de amendoim usado errado',
  'Cocaína de má qualidade',
  'Maconha do primo',
  'Um remédio que ninguém sabe pra que serve',
  'Álcool em gel de sobremesa',
  'Uma bexiga cheia e três horas de trânsito',
  'A mulher do vizinho',
  'O marido da vizinha',
  'Trocar de casal na sexta-feira',
  'Um casamento arranjado',
  'Fingir que gosta de jazz',
  'Reunião de família com projetor',
  'A ditadura do proletariado',
  'Um golpe de estado bem-humorado',
  'Um discurso motivacional de meia hora',
  'Uma faca cega e muita disposição',
  'Um saco de gatos',
  'Homens chorando',
  'Um exército de crianças mal-educadas',
  'A polícia batendo na porta',
  'Um cachorro-quente de rodoviária',
  'Uma banana esquecida na mochila',
  'Um enterro alegre demais',
  'Uma piada racista contada pelo tio',
  'O grupo do trabalho às onze da noite',
  'Um pedido de desculpa por áudio',
  'Uma tatuagem de nome de ex',
  'Um cara com uma van sem janela',
  'Um curso de coaching',
  'Uma reunião de condomínio às sete da manhã',
  'Um velório com bufê ruim',
  'Um karaokê de música sertaneja às cinco da manhã',
  'Um roubo de identidade',
  'Chorar assistindo propaganda de margarina',
  'Sonhar com o próprio enterro',
  'Uma cirurgia estética que deu errado',
  'A menopausa chegando na hora errada',
  'Um infarto no meio do churrasco',
  'A minha certidão de óbito',
  'O apocalipse zumbi',
  'Um vazamento de gás em família',
  'Um segredo de estado guardado num grupo de WhatsApp',
  'Dez mil abelhas dentro de um carro',
  'Meu chefe pelado',
  'Um estágio não remunerado',
  'A fila de um pronto-socorro numa madrugada de domingo',
  'Um assalto malfeito',
  'A minha declaração de amor rejeitada em público',
  'Uma noite inteira sem sinal de celular',
  'Um cachorro que sabe demais',
  'A vingança servida fria e mal cozida',
  'Um exorcismo caseiro',
  'Uma tempestade de granizo no dia do casamento',
  'A minha lista de bloqueados',
  'Uma bomba relógio muito educada',
  'Um baralho marcado',
  'Duas colheres de sopa de arrependimento',
  'Um discurso no altar interrompido',
  'A conta do bar dividida igualmente',
  'Uma promessa feita bêbado',
  'O rim que eu ainda tenho',
]

/** `CCT-31`, `CCT-33` — os pacotes disponíveis, separados por tom. */
export const CARTAS_TURMA: PacoteDeCartasTurma[] = [
  {
    id: 'cartas-roda-de-amigos',
    emoji: '🍿',
    nome: 'Roda de Amigos',
    descricao: 'Dá pra jogar com a família na sala. Tom leve.',
    quantidade: RODA_DE_AMIGOS_PERGUNTAS.length + RODA_DE_AMIGOS_RESPOSTAS.length,
    jogoId: 'cartas-contra-a-turma',
    tom: 'leve',
    perguntas: RODA_DE_AMIGOS_PERGUNTAS,
    respostas: RODA_DE_AMIGOS_RESPOSTAS,
  },
  {
    id: 'cartas-sem-filtro',
    emoji: '🚬',
    nome: 'Sem Filtro',
    descricao: 'Dívida, ressaca e crise existencial. Tom pesado, mesa adulta.',
    quantidade: SEM_FILTRO_PERGUNTAS.length + SEM_FILTRO_RESPOSTAS.length,
    jogoId: 'cartas-contra-a-turma',
    tom: 'pesado',
    perguntas: SEM_FILTRO_PERGUNTAS,
    respostas: SEM_FILTRO_RESPOSTAS,
  },
  {
    id: 'cartas-toxico',
    emoji: '☣️',
    nome: 'Tóxico',
    descricao: 'Sexo ruim, morte e vergonha sem saída. Mesa adulta e amizade de longa data.',
    quantidade: TOXICO_PERGUNTAS.length + TOXICO_RESPOSTAS.length,
    jogoId: 'cartas-contra-a-turma',
    tom: 'toxico',
    perguntas: TOXICO_PERGUNTAS,
    respostas: TOXICO_RESPOSTAS,
  },
  {
    id: 'cartas-classico',
    emoji: '🃏',
    nome: 'O Clássico',
    descricao: 'O baralho que deu origem ao gênero, em português. Tom tóxico, mesa adulta.',
    creditos:
      'Tradução e adaptação de Cards Against Humanity, de Cards Against Humanity LLC, sob CC BY-NC-SA 2.0. Esta versão está sob a mesma licença.',
    quantidade: CLASSICO_PERGUNTAS.length + CLASSICO_RESPOSTAS.length,
    jogoId: 'cartas-contra-a-turma',
    tom: 'toxico',
    perguntas: CLASSICO_PERGUNTAS,
    respostas: CLASSICO_RESPOSTAS,
  },
]
