import type { Dificuldade, PacoteResumo } from './protocolo'

export type { Dificuldade }

export interface CartaDoPacote {
  texto: string
  dificuldade: Dificuldade
}

export interface PacoteCompleto extends PacoteResumo {
  cartas: CartaDoPacote[]
}

/** `PKT2-18` — monta as 150 cartas de um pacote a partir de três listas de 50 (fácil/médio/difícil). */
function cartas(facil: string[], medio: string[], dificil: string[]): CartaDoPacote[] {
  return [
    ...facil.map((texto): CartaDoPacote => ({ texto, dificuldade: 'facil' })),
    ...medio.map((texto): CartaDoPacote => ({ texto, dificuldade: 'medio' })),
    ...dificil.map((texto): CartaDoPacote => ({ texto, dificuldade: 'dificil' })),
  ]
}

export const PACOTES: PacoteCompleto[] = [
  {
    id: 'filmes',
    emoji: '🎥',
    nome: 'Filmes',
    descricao: 'Adivinhe os filmes mais famosos do cinema.',
    quantidade: 150,
    cartas: cartas(
      [
        'Titanic', 'Star Wars', 'Harry Potter e a Pedra Filosofal', 'O Rei Leão', 'Shrek',
        'Toy Story', 'Vingadores: Ultimato', 'Homem-Aranha', 'Batman', 'Jurassic Park',
        'De Volta para o Futuro', 'Matrix', 'O Poderoso Chefão', 'Frozen', 'Procurando Nemo',
        'A Bela e a Fera', 'Aladdin', 'Branca de Neve e os Sete Anões', 'Cinderela', 'E.T. O Extraterrestre',
        'Tubarão', 'Rocky', 'Karatê Kid', 'Homem de Ferro', 'Pantera Negra',
        'Divertida Mente', 'Coco', 'Moana', 'Encanto', 'Barbie',
        'Oppenheimer', 'Duna', 'Coringa', 'Gladiador', 'Piratas do Caribe',
        'Missão Impossível', 'Velozes e Furiosos', 'Meu Malvado Favorito', 'A Era do Gelo', 'Madagascar',
        'Kung Fu Panda', 'Como Treinar o Seu Dragão', 'Cidade de Deus', 'Tropa de Elite', 'Central do Brasil',
        'Minha Mãe é uma Peça', 'Vai Que Cola', 'O Auto da Compadecida', 'Turma da Mônica', 'Homem-Aranha: Através do Aranhaverso',
      ],
      [
        'Clube da Luta', 'Pulp Fiction', 'Forrest Gump', 'Interestelar', 'A Origem',
        'O Iluminado', 'Psicose', 'O Silêncio dos Inocentes', 'Seven', 'Os Suspeitos',
        'O Sexto Sentido', 'O Show de Truman', 'Cisne Negro', 'Whiplash', 'La La Land',
        'Guardiões da Galáxia', 'Doutor Estranho', 'Thor: Ragnarok', 'Logan', 'Deadpool',
        'Kingsman', 'John Wick', 'Corra!', 'Nós', 'Hereditário',
        'Sexta-Feira 13', 'Halloween', 'A Freira', 'Invocação do Mal', 'Atividade Paranormal',
        'Jogos Mortais', 'Náufrago', 'Gravidade', 'Perdido em Marte', 'Extermínio',
        'Guerra Mundial Z', 'Corrida Contra a Morte', 'Se Beber Não Case', 'Como Eu Era Antes de Você', 'A Culpa é das Estrelas',
        'Diário de uma Paixão', 'Simplesmente Amor', 'O Discurso do Rei', 'Doze Homens e uma Sentença', 'Um Sonho Possível',
        'O Lado Bom da Vida', 'Green Book', 'Bacurau', 'Aquarius', 'Que Horas Ela Volta?',
      ],
      [
        'Solaris', 'Stalker', 'Persona', 'O Sétimo Selo', 'Cidadão Kane',
        'Rashomon', 'Ladrões de Bicicleta', 'O Encouraçado Potemkin', 'Metropolis', '2001: Uma Odisseia no Espaço',
        'Blade Runner', 'Apocalypse Now', 'Taxi Driver', 'O Bom, o Mau e o Feio', 'Era uma Vez no Oeste',
        'Amadeus', 'Barry Lyndon', 'Laranja Mecânica', 'Full Metal Jacket', 'O Grande Ditador',
        'Tempos Modernos', 'A Regra do Jogo', 'Um Corpo que Cai', 'Janela Indiscreta', 'Intriga Internacional',
        'Os Pássaros', 'Crepúsculo dos Deuses', 'Casablanca', 'Cantando na Chuva', 'Fantasia',
        'O Mágico de Oz', 'Ben-Hur', 'Lawrence da Arábia', 'Doutor Jivago', 'A Ponte do Rio Kwai',
        'Grande Hotel Budapeste', 'Moonrise Kingdom', 'Amélie Poulain', 'Tropa de Elite 2', 'O Som ao Redor',
        'Bicho de Sete Cabeças', 'Cabra Marcado para Morrer', 'Terra em Transe', 'Deus e o Diabo na Terra do Sol', 'O Pagador de Promessas',
        'O Homem que Copiava', 'Boi Neon', 'Zama', 'A Vida Invisível', 'Divino Amor',
      ],
    ),
  },
  {
    id: 'anime',
    emoji: '⛩️',
    nome: 'Personagens de Anime',
    descricao: 'Personagens icônicos do mundo dos animes e mangás.',
    quantidade: 150,
    cartas: cartas(
      [
        'Goku', 'Naruto', 'Luffy', 'Pikachu', 'Sasuke',
        'Ash Ketchum', 'Vegeta', 'Sailor Moon', 'Totoro', 'Doraemon',
        'Kirito', 'Asuna', 'Tanjiro', 'Nezuko', 'Zenitsu',
        'Eren Yeager', 'Mikasa Ackerman', 'Levi Ackerman', 'Light Yagami', 'L',
        'Ichigo Kurosaki', 'Natsu Dragneel', 'Edward Elric', 'Alphonse Elric', 'Saitama',
        'Deku', 'Bakugo', 'All Might', 'Gojo Satoru', 'Anya Forger',
        'Loid Forger', 'Yor Forger', 'Chopper', 'Nami', 'Zoro',
        'Sanji', 'Robin', 'Chihiro', 'Howl', 'Kiki',
        'Meowth', 'Misty', 'Brock', 'Bulma', 'Piccolo',
        'Freeza', 'Cell', 'Majin Boo', 'Trunks', 'Gohan',
      ],
      [
        'Itachi Uchiha', 'Kakashi Hatake', 'Jiraiya', 'Gaara', 'Hinata Hyuga',
        'Shikamaru', 'Rock Lee', 'Killua Zoldyck', 'Gon Freecss', 'Hisoka',
        'Meruem', 'Jotaro Kujo', 'Dio Brando', 'Josuke Higashikata', 'Giorno Giovanna',
        'Spike Spiegel', 'Faye Valentine', 'Lelouch Lamperouge', 'C.C.', 'Shinji Ikari',
        'Asuka Langley', 'Rei Ayanami', 'Inosuke Hashibira', 'Muzan Kibutsuji', 'Rengoku',
        'Uzui Tengen', 'Shanks', 'Ace', 'Law', 'Doflamingo',
        'Big Mom', 'Kaido', 'Erza Scarlet', 'Gray Fullbuster', 'Lucy Heartfilia',
        'Winry Rockbell', 'Roy Mustang', 'Sung Jin-Woo', 'Denji', 'Power',
        'Makima', 'Aki Hayakawa', 'Rimuru Tempest', 'Megumin', 'Aqua',
        'Kazuma', 'Violet Evergarden', 'Yuji Itadori', 'Megumi Fushiguro', 'Nobara Kugisaki',
      ],
      [
        'Guts', 'Griffith', 'Casca', 'Ken Kaneki', 'Touka Kirishima',
        'Kenshin Himura', 'Vash the Stampede', 'Alucard', 'Integra Hellsing', 'Simon',
        'Kamina', 'Yoko Littner', 'Homura Akemi', 'Madoka Kaname', 'Sayaka Miki',
        'Revy', 'Rock', 'Thorfinn', 'Askeladd', 'Joseph Joestar',
        'Jonathan Joestar', 'Kars', 'Yoshikage Kira', 'Char Aznable', 'Amuro Ray',
        'Motoko Kusanagi', 'Batou', 'Edward Wong Hau Pepelu Tivrusky IV', 'Isaac Netero', 'Chrollo Lucilfer',
        'Kurapika', 'Leorio', 'Feitan', 'Machi', 'Franklin',
        'Grimmjow Jaegerjaquez', 'Aizen Sosuke', 'Byakuya Kuchiki', 'Rukia Kuchiki', 'Renji Abarai',
        'Toshiro Hitsugaya', 'Ulquiorra Cifer', 'Nagato', 'Obito Uchiha', 'Madara Uchiha',
        'Orochimaru', 'Tsunade', 'Might Guy', 'Sasori', 'Deidara',
      ],
    ),
  },
  {
    id: 'personagens-filmes',
    emoji: '🍿',
    nome: 'Personagens de Filmes',
    descricao: 'Heróis, vilões e personagens inesquecíveis.',
    quantidade: 150,
    cartas: cartas(
      [
        'Darth Vader', 'Luke Skywalker', 'Harry Potter', 'Hermione Granger', 'Ron Weasley',
        'Voldemort', 'Homem-Aranha', 'Batman', 'Coringa', 'Superman',
        'Mulher-Maravilha', 'Capitão América', 'Homem de Ferro', 'Thor', 'Hulk',
        'Wolverine', 'Shrek', 'Fiona', 'Burro (Shrek)', 'Woody',
        'Buzz Lightyear', 'Simba', 'Elsa', 'Olaf', 'Aladdin',
        'Jasmine', 'Gênio', 'Mufasa', 'Nemo', 'Dory',
        'Jack Sparrow', 'Indiana Jones', 'James Bond', 'Rocky Balboa', 'Forrest Gump',
        'Neo', 'John Wick', 'Gandalf', 'Frodo Bolseiro', 'Aragorn',
        'Gollum', 'Yoda', 'Chewbacca', 'Han Solo', 'Princesa Leia',
        'E.T.', 'Miles Morales', 'Katniss Everdeen', 'Hagrid', 'Kevin McCallister',
      ],
      [
        'Tyler Durden', 'Hannibal Lecter', 'Norman Bates', 'Jack Torrance', 'Michael Corleone',
        'Vito Corleone', 'Tony Montana', 'Travis Bickle', 'Vincent Vega', 'Jules Winnfield',
        'Ellen Ripley', 'Sarah Connor', 'T-800', 'Marty McFly', 'Doc Brown',
        'Rick Deckard', 'Roy Batty', 'Clarice Starling', 'Amy Dunne', 'Nina Sayers',
        'Andy Dufresne', 'Red', 'Truman Burbank', 'Max Rockatansky', 'Furiosa',
        'Deadpool', 'Logan', 'Doutor Estranho', 'Loki', 'Thanos',
        'Gamora', 'Rocket Raccoon', 'Groot', 'T\'Challa', 'Peter Parker',
        'Tony Stark', 'Bruce Wayne', 'Arthur Fleck', 'Harley Quinn', 'Bane',
        'Ra\'s al Ghul', 'Alfred Pennyworth', 'Bilbo Bolseiro', 'Legolas', 'Gimli',
        'Boromir', 'Sauron', 'Saruman', 'Peeta Mellark', 'Gale Hawthorne',
      ],
      [
        'Randle McMurphy', 'Rooster Cogburn', 'Atticus Finch', 'Michael Myers', 'Freddy Krueger',
        'Jason Voorhees', 'Pinhead', 'Leatherface', 'Chucky', 'Annabelle',
        'Regan MacNeil', 'Carrie White', 'Danny Torrance', 'Alex DeLarge', 'HAL 9000',
        'Dave Bowman', 'Roy Neary', 'Ellie Arroway', 'Cooper', 'Murph',
        'TARS', 'Bishop', 'Ash', 'Newt', 'John Connor',
        'Kyle Reese', 'Rorschach', 'Doutor Manhattan', 'Two-Face', 'Selina Kyle',
        'Edward Nygma', 'Oswald Cobblepot', 'Ozymandias', 'O Comediante', 'Eric Draven',
        'V', 'Evey Hammond', 'Amélie Poulain', 'Jean Valjean', 'Javert',
        'Fantine', 'Cosette', 'Willy Wonka', 'Charlie Bucket', 'Edward Mãos de Tesoura',
        'Beetlejuice', 'Jack Skellington', 'Sally', 'Barão Munchausen', 'Nosferatu',
      ],
    ),
  },
  {
    id: 'livros',
    emoji: '📚',
    nome: 'Livros',
    descricao: 'Clássicos da literatura, best-sellers e romances.',
    quantidade: 150,
    cartas: cartas(
      [
        'Dom Quixote', '1984', 'O Pequeno Príncipe', 'Harry Potter e a Pedra Filosofal', 'O Senhor dos Anéis',
        'O Hobbit', 'O Alquimista', 'Cem Anos de Solidão', 'A Revolução dos Bichos', 'Crime e Castigo',
        'A Metamorfose', 'Orgulho e Preconceito', 'O Morro dos Ventos Uivantes', 'Moby Dick', 'A Divina Comédia',
        'O Conde de Monte Cristo', 'Os Miseráveis', 'Frankenstein', 'Drácula', 'Alice no País das Maravilhas',
        'O Retrato de Dorian Gray', 'O Grande Gatsby', 'Admirável Mundo Novo', 'Fahrenheit 451', 'O Apanhador no Campo de Centeio',
        'A Menina que Roubava Livros', 'O Código Da Vinci', 'Anjos e Demônios', 'A Guerra dos Tronos', 'O Nome do Vento',
        'Duna', 'Fundação', 'Eu, Robô', 'O Guia do Mochileiro das Galáxias', 'Jogos Vorazes',
        'Crepúsculo', 'Percy Jackson', 'Dom Casmurro', 'Memórias Póstumas de Brás Cubas', 'O Cortiço',
        'Capitães da Areia', 'Vidas Secas', 'Grande Sertão: Veredas', 'A Hora da Estrela', 'A Culpa é das Estrelas',
        'Diário de um Banana', 'Percy Jackson e o Ladrão de Raios', 'As Crônicas de Nárnia', 'As Aventuras de Huckleberry Finn', 'O Diário de Anne Frank',
      ],
      [
        'Ulisses', 'Guerra e Paz', 'Anna Karenina', 'Os Irmãos Karamázov', 'O Idiota',
        'Em Busca do Tempo Perdido', 'O Processo', 'O Castelo', 'A Náusea', 'O Estrangeiro',
        'A Peste', 'O Outono do Patriarca', 'O Amor nos Tempos do Cólera', 'A Casa dos Espíritos', 'Como Água para Chocolate',
        'A Insustentável Leveza do Ser', 'Os Sofrimentos do Jovem Werther', 'Fausto', 'Madame Bovary', 'O Vermelho e o Negro',
        'Middlemarch', 'Jane Eyre', 'Persuasão', 'Sentido e Sensibilidade', 'A Letra Escarlate',
        'As Vinhas da Ira', 'Ratos e Homens', 'Matadouro 5', 'Laranja Mecânica', 'O Senhor das Moscas',
        'Nunca Me Deixe Ir', 'Ensaio Sobre a Cegueira', 'O Homem Duplicado', 'A Torre Negra', 'It: A Coisa',
        'O Iluminado', 'Duna Messias', 'Neuromancer', 'Eu Sou a Lenda', 'A Mão Esquerda da Escuridão',
        'Iracema', 'O Guarani', 'Senhora', 'Memórias de um Sargento de Milícias', 'Quincas Borba',
        'Laços de Família', 'Perto do Coração Selvagem', 'A Paixão Segundo G.H.', 'Torto Arado', 'Água Viva',
      ],
      [
        'Finnegans Wake', 'O Som e a Fúria', 'Absalão, Absalão!', 'Luz de Agosto', 'À Sombra das Moças em Flor',
        'O Nome da Rosa', 'Se um Viajante numa Noite de Inverno', 'As Cidades Invisíveis', 'O Barão nas Árvores', 'Cem Sonetos de Amor',
        'A Montanha Mágica', 'Doutor Fausto', 'Buddenbrooks', 'Os Demônios', 'Recordações da Casa dos Mortos',
        'Confissões de um Fidalgo', 'Bartleby, o Escrivão', 'Billy Budd', 'A Escrivaninha', 'Os Sertões',
        'Memorial de Maria Moura', 'O Tempo e o Vento', 'O Continente', 'Sagarana', 'Primeiras Estórias',
        'Tutameia', 'Corpo de Baile', 'A Hora e a Vez de Augusto Matraga', 'Angústia', 'São Bernardo',
        'Fogo Morto', 'Menino de Engenho', 'Doidinho', 'Bangüê', 'Usina',
        'O Ateneu', 'Recordações do Escrivão Isaías Caminha', 'Triste Fim de Policarpo Quaresma', 'Os Bruzundangas', 'Canaã',
        'A Cidade e as Serras', 'Os Maias', 'O Primo Basílio', 'A Relíquia', 'Amor de Perdição',
        'Amanhecer Esmeralda', 'Netto Perde sua Alma', 'Passar a Limpo', 'A Última Quimera', 'Um Copo de Cólera',
      ],
    ),
  },
  {
    id: 'futebol',
    emoji: '⚽',
    nome: 'Jogadores de Futebol',
    descricao: 'Lendas do passado e craques da atualidade.',
    quantidade: 150,
    cartas: cartas(
      [
        'Pelé', 'Maradona', 'Messi', 'Cristiano Ronaldo', 'Neymar',
        'Ronaldinho Gaúcho', 'Ronaldo Fenômeno', 'Zidane', 'Romário', 'Zico',
        'Rivellino', 'Garrincha', 'Sócrates', 'Taffarel', 'Cafu',
        'Roberto Carlos', 'Kaká', 'Vini Jr.', 'Rodrygo', 'Mbappé',
        'Haaland', 'De Bruyne', 'Salah', 'Lewandowski', 'Sergio Ramos',
        'Casillas', 'Beckham', 'Suárez', 'Cavani', 'Vitinho',
        'Gabigol', 'Hulk', 'Fred', 'Marta', 'Formiga',
        'Cristiane', 'Falcão (futsal)', 'Zagallo', 'Bebeto', 'Dunga',
        'Careca', 'Jairzinho', 'Tostão', 'Nilton Santos', 'Djalma Santos',
        'Vavá', 'Leônidas da Silva', 'Kléberson', 'Hernanes', 'David Luiz',
      ],
      [
        'Iniesta', 'Xavi', 'Puyol', 'Maldini', 'Buffon',
        'Neuer', 'Modric', 'Kroos', 'Cruyff', 'Beckenbauer',
        'Platini', 'Di Stéfano', 'Puskás', 'Eusébio', 'Bobby Charlton',
        'George Best', 'Van Basten', 'Gullit', 'Rijkaard', 'Baggio',
        'Del Piero', 'Totti', 'Del Bosque', 'Xabi Alonso', 'Fábregas',
        'Piqué', 'Busquets', 'Griezmann', 'Benzema', 'Pogba',
        'Kanté', 'Mané', 'Aubameyang', 'Sterling', 'Foden',
        'Bellingham', 'Casemiro', 'Fabinho', 'Alisson', 'Ederson',
        'Thiago Silva', 'Marquinhos', 'Alex Sandro', 'Danilo', 'Everton Ribeiro',
        'Arrascaeta', 'Gerson', 'Paquetá', 'Raphinha', 'Antony',
      ],
      [
        'Heleno de Freitas', 'Friedenreich', 'Domingos da Guia', 'Ademir de Menezes', 'Zizinho',
        'Julinho Botelho', 'Didi', 'Gilmar dos Santos Neves', 'Bellini', 'Amarildo',
        'Alcindo', 'Roberto Dinamite', 'Éder Aleixo', 'Paulo Roberto Falcão', 'Casagrande',
        'Renato Gaúcho', 'Müller', 'Raí', 'Leonardo', 'Mazinho',
        'Aldair', 'Júnior Baiano', 'Márcio Santos', 'Viola', 'Mauro Silva',
        'Zé Roberto', 'Denílson', 'Edmundo', 'Djalminha', 'Sávio',
        'Juninho Paulista', 'Emerson Leão', 'Rogério Ceni', 'Marcos (goleiro)', 'Dida',
        'Júlio César', 'Lúcio', 'Roque Júnior', 'Belletti', 'Gilberto Silva',
        'Adriano Imperador', 'Alex (Fenerbahçe)', 'Robinho', 'Pato', 'Willian',
        'Ganso', 'Elano', 'Nilmar', 'Luís Fabiano', 'Vágner Love',
      ],
    ),
  },
  {
    id: 'jogos',
    emoji: '🎮',
    nome: 'Jogos',
    descricao: 'Títulos clássicos e sucessos modernos.',
    quantidade: 150,
    cartas: cartas(
      [
        'Super Mario World', 'Sonic the Hedgehog', 'The Legend of Zelda', 'Minecraft', 'Grand Theft Auto V',
        'Tetris', 'Pac-Man', 'Street Fighter II', 'Mortal Kombat', 'Call of Duty',
        'Counter-Strike', 'League of Legends', 'Dota 2', 'World of Warcraft', 'Overwatch',
        'Valorant', 'Fortnite', 'PUBG', 'Free Fire', 'Roblox',
        'The Sims', 'Red Dead Redemption 2', 'The Witcher 3', 'Skyrim', 'Dark Souls',
        'Elden Ring', 'God of War', 'The Last of Us', 'Uncharted', 'Resident Evil',
        'Silent Hill', 'Metal Gear Solid', 'Final Fantasy VII', 'Pokémon Vermelho/Azul', 'Super Smash Bros',
        'Mario Kart 8', 'Animal Crossing', 'Hollow Knight', 'Hades', 'Celeste',
        'FIFA', 'Fifa 23 (agora EA FC)', 'Rocket League', 'Among Us', 'Genshin Impact',
        'Candy Crush', 'Angry Birds', 'Subway Surfers', 'Clash Royale', 'Stardew Valley',
      ],
      [
        'Half-Life', 'Half-Life 2', 'Portal', 'Bioshock', 'Doom',
        'Quake', 'Diablo', 'Diablo II', 'StarCraft', 'Warcraft III',
        'The Elder Scrolls IV: Oblivion', 'Fallout 3', 'Fallout: New Vegas', 'Mass Effect', 'Dragon Age',
        'Assassin\'s Creed', 'Assassin\'s Creed II', 'Far Cry 3', 'Watch Dogs', 'Cyberpunk 2077',
        'Death Stranding', 'Sekiro', 'Bloodborne', 'Demon\'s Souls', 'Nier: Automata',
        'Persona 5', 'Kingdom Hearts', 'Chrono Trigger', 'Super Metroid', 'Castlevania: Symphony of the Night',
        'Ori and the Blind Forest', 'Cuphead', 'Undertale', 'Terraria', 'Don\'t Starve',
        'Slay the Spire', 'Portal 2', 'Left 4 Dead', 'Titanfall 2', 'Apex Legends',
        'Splatoon', 'Super Mario Odyssey', 'The Legend of Zelda: Breath of the Wild', 'Metroid Prime', 'Ratchet & Clank',
        'Crash Bandicoot', 'Spyro the Dragon', 'Banjo-Kazooie', 'Conker\'s Bad Fur Day', 'Jak and Daxter',
      ],
      [
        'System Shock 2', 'Planescape: Torment', 'Baldur\'s Gate II', 'Deus Ex', 'Vampire: The Masquerade – Bloodlines',
        'Ico', 'Shadow of the Colossus', 'Katamari Damacy', 'Rez', 'Panzer Dragoon Saga',
        'Silent Hill 2', 'Suikoden II', 'Xenogears', 'Vagrant Story', 'Final Fantasy Tactics',
        'Radiant Silvergun', 'Ikaruga', 'Gunstar Heroes', 'Contra III', 'Actraiser',
        'EarthBound', 'Mother 3', 'Secret of Mana', 'Chrono Cross', 'Grandia',
        'Panzer Dragoon', 'Nights into Dreams', 'Jet Set Radio', 'ToeJam & Earl', 'Streets of Rage 2',
        'Golden Axe', 'Shinobi', 'Gunstar Future Heroes', 'Advance Wars', 'Fire Emblem: Path of Radiance',
        'Front Mission', 'Ogre Battle', 'Tactics Ogre', 'Disgaea', 'Valkyria Chronicles',
        'The Longest Journey', 'Grim Fandango', 'Full Throttle', 'Day of the Tentacle', 'Sam & Max Hit the Road',
        'Monkey Island', 'King\'s Quest', 'Space Quest', 'Loom', 'Zork',
      ],
    ),
  },
  {
    id: 'personagens-jogos',
    emoji: '👾',
    nome: 'Personagens de Jogos',
    descricao: 'Protagonistas e vilões marcantes dos games.',
    quantidade: 150,
    cartas: cartas(
      [
        'Mario', 'Luigi', 'Bowser', 'Peach', 'Sonic',
        'Tails', 'Knuckles', 'Eggman', 'Link', 'Zelda',
        'Ganon', 'Pikachu', 'Charizard', 'Mewtwo', 'Samus Aran',
        'Donkey Kong', 'Kirby', 'Master Chief', 'Kratos', 'Geralt de Rivia',
        'Lara Croft', 'Nathan Drake', 'Joel', 'Ellie', 'Solid Snake',
        'Cloud Strife', 'Sephiroth', 'Sub-Zero', 'Scorpion', 'Ryu',
        'Ken', 'Chun-Li', 'Arthur Morgan', 'John Marston', 'Doomguy',
        'Gordon Freeman', 'GLaDOS', 'Steve', 'Tracer', 'Jinx',
        'Ashe', 'Yasuo', 'Teemo', 'Pac-Man', 'Ryu Hayabusa',
        'Crash Bandicoot', 'Spyro', 'Banjo', 'Kazooie', 'Rayman',
      ],
      [
        'Dante (Devil May Cry)', 'Vergil', 'Bayonetta', 'Raiden (Metal Gear)', 'Big Boss',
        'Revolver Ocelot', 'Psycho Mantis', 'Sniper Wolf', 'Chief Elizabeth', 'Booker DeWitt',
        'Andrew Ryan', 'BJ Blazkowicz', 'Doom Slayer', 'Isaac Clarke', 'Alma Wade',
        'Leon Kennedy', 'Chris Redfield', 'Jill Valentine', 'Ada Wong', 'Albert Wesker',
        'Nemesis', 'Pyramid Head', 'Heather Mason', 'James Sunderland', 'Alucard (Castlevania)',
        'Simon Belmont', 'Trevor Belmont', 'Dracula (Castlevania)', 'Ryu (Street Fighter)', 'Guile',
        'M. Bison', 'Akuma', 'Cammy', 'Kazuya Mishima', 'Heihachi Mishima',
        'Jin Kazama', 'Nina Williams', 'Yoshimitsu', 'Terry Bogard', 'Kyo Kusanagi',
        'Iori Yagami', 'Liu Kang', 'Raiden (Mortal Kombat)', 'Kitana', 'Mileena',
        'Shao Kahn', 'Baraka', 'Johnny Cage', 'Geralt (Witcher)', 'Yennefer',
      ],
      [
        'Adam Jensen', 'JC Denton', 'Garrett (Thief)', 'Corvo Attano', 'Emily Kaldwin',
        'BJ Blazkowicz (Wolfenstein)', 'The Boss (Metal Gear)', 'Gray Fox', 'Vamp', 'Liquid Snake',
        'Nathan Hale (Resistance)', 'Sarge (Halo)', 'Cortana', 'Arbiter', '343 Guilty Spark',
        'Marcus Fenix', 'Dominic Santiago', 'General RAAM', 'Nathan Spencer (Bionic Commando)', 'Samus (Metroid Prime)',
        'Ridley', 'Dark Samus', 'Meta Knight', 'King Dedede', 'Fox McCloud',
        'Falco Lombardi', 'Captain Falcon', 'Ike', 'Marth', 'Roy',
        'Pit', 'Ness', 'Lucas', 'Olimar', 'Wario',
        'Waluigi', 'Toad', 'Yoshi', 'Diddy Kong', 'King K. Rool',
        'Conker', 'Jak', 'Aloy', 'Sly Cooper', 'Bentley',
        'Murray', 'Ratchet', 'Clank', 'Sackboy', 'Comandante Shepard',
      ],
    ),
  },
  {
    id: 'series',
    emoji: '📺',
    nome: 'Séries de TV',
    descricao: 'Shows que marcaram época e séries atuais.',
    quantidade: 150,
    cartas: cartas(
      [
        'Breaking Bad', 'Game of Thrones', 'Stranger Things', 'Friends', 'The Office',
        'How I Met Your Mother', 'Seinfeld', 'The Simpsons', 'South Park', 'Rick and Morty',
        'Peaky Blinders', 'The Boys', 'Black Mirror', 'Dark', 'La Casa de Papel',
        'Round 6', 'Narcos', 'House', 'Grey\'s Anatomy', 'Supernatural',
        'The Walking Dead', 'Lost', 'Prison Break', 'Dexter', 'True Detective',
        'Fargo', 'Better Call Saul', 'Succession', 'The Last of Us', 'The Mandalorian',
        'WandaVision', 'Loki', 'The Crown', 'Bridgerton', 'Euphoria',
        'Chaves', 'Chapolin', 'A Grande Família', 'Os Normais', 'Tapas & Beijos',
        'Wednesday', 'Cobra Kai', 'Emily em Paris', 'You', 'Sex Education',
        'Ted Lasso', 'Ozark', 'Yellowstone', 'Vikings', 'Round 6 (Squid Game)',
      ],
      [
        'Sopranos', 'The Wire', 'Mad Men', 'Twin Peaks', 'Six Feet Under',
        'Deadwood', 'Curb Your Enthusiasm', 'Arrested Development', 'Community', 'Parks and Recreation',
        'It\'s Always Sunny in Philadelphia', 'Brooklyn Nine-Nine', 'Modern Family', 'Malcolm in the Middle', 'That \'70s Show',
        'Battlestar Galactica', 'Firefly', 'The X-Files', 'Buffy the Vampire Slayer', 'Angel',
        'Sherlock', 'Doctor Who', 'Downton Abbey', 'The Handmaid\'s Tale', 'Westworld',
        'Mr. Robot', 'Homeland', 'The Americans', 'Rectify', 'Halt and Catch Fire',
        'BoJack Horseman', 'Big Little Lies', 'Sharp Objects', 'Chernobyl', 'Band of Brothers',
        'The Pacific', 'Outlander', 'Poldark', 'Sense8', 'Orange Is the New Black',
        'Elite', 'Dark Desire', 'Cable Girls', 'Gilmore Girls', 'Boardwalk Empire',
        'Justified', 'Longmire', 'Sons of Anarchy', 'Vis a Vis', 'Merlí',
      ],
      [
        'The Leftovers', 'Terriers', 'Party Down', 'Freaks and Geeks', 'My So-Called Life',
        'The Wonder Years', 'St. Elsewhere', 'Homicide: Life on the Street', 'NYPD Blue', 'Hill Street Blues',
        'The Shield', 'Oz', 'Carnivàle', 'Rome', 'Enlightened',
        'Getting On', 'Bored to Death', 'Flight of the Conchords', 'Look Around You', 'The Mighty Boosh',
        'Nathan for You', 'Review', 'Fleabag', 'Catastrophe', 'This Country',
        'Detectorists', 'The Trip', 'Pen15', 'Atlanta', 'Insecure',
        'Barry', 'Undone', 'Russian Doll', 'Search Party', 'The Good Place',
        'Forever', 'Made for Love', 'Pachinko', 'Severance', 'The Bear',
        'Beef', 'Reservation Dogs', 'What We Do in the Shadows', 'I Think You Should Leave', 'Portlandia',
        'Mindhunter', 'The Killing', 'Broadchurch', 'High Maintenance', 'Happy Valley',
      ],
    ),
  },
  {
    id: 'musica',
    emoji: '🎤',
    nome: 'Cantores/Bandas',
    descricao: 'Ídolos da música, bandas e lendas do rock.',
    quantidade: 150,
    cartas: cartas(
      [
        'Michael Jackson', 'Elvis Presley', 'Freddie Mercury', 'Madonna', 'Beyoncé',
        'Taylor Swift', 'Justin Bieber', 'Ed Sheeran', 'Adele', 'Lady Gaga',
        'Rihanna', 'Katy Perry', 'Bruno Mars', 'Eminem', 'Snoop Dogg',
        'Tupac', 'The Beatles', 'Rolling Stones', 'Queen', 'Nirvana',
        'Metallica', 'AC/DC', 'Pink Floyd', 'Led Zeppelin', 'Guns N\' Roses',
        'Red Hot Chili Peppers', 'Coldplay', 'U2', 'Linkin Park', 'Green Day',
        'Roberto Carlos', 'Caetano Veloso', 'Gilberto Gil', 'Chico Buarque', 'Tim Maia',
        'Jorge Ben Jor', 'Legião Urbana', 'Charlie Brown Jr.', 'Skank', 'Titãs',
        'Anitta', 'Ivete Sangalo', 'Marília Mendonça', 'Gusttavo Lima', 'Luan Santana',
        'Wesley Safadão', 'Alok', 'Racionais MC\'s', 'Emicida', 'Djonga',
      ],
      [
        'David Bowie', 'Prince', 'Whitney Houston', 'Mariah Carey', 'Celine Dion',
        'Amy Winehouse', 'Alicia Keys', 'Sia', 'Billie Eilish', 'Dua Lipa',
        'The Weeknd', 'Drake', 'Kendrick Lamar', 'Jay-Z', 'Kanye West',
        'Beastie Boys', 'Run-D.M.C.', 'Public Enemy', 'Wu-Tang Clan', 'Notorious B.I.G.',
        'Frank Sinatra', 'Ella Fitzgerald', 'Louis Armstrong', 'Ray Charles', 'Aretha Franklin',
        'Stevie Wonder', 'Marvin Gaye', 'James Brown', 'Bob Marley', 'Jimi Hendrix',
        'Janis Joplin', 'The Doors', 'The Who', 'Black Sabbath', 'Deep Purple',
        'Iron Maiden', 'Judas Priest', 'Slayer', 'Megadeth', 'Pantera',
        'System of a Down', 'Rage Against the Machine', 'Foo Fighters', 'Radiohead', 'Muse',
        'Arctic Monkeys', 'The Strokes', 'Vampire Weekend', 'Tame Impala', 'Cazuza',
      ],
      [
        'John Coltrane', 'Miles Davis', 'Thelonious Monk', 'Charlie Parker', 'Duke Ellington',
        'Nina Simone', 'Billie Holiday', 'Nat King Cole', 'Sarah Vaughan', 'Chet Baker',
        'Kraftwerk', 'Brian Eno', 'Talking Heads', 'Joy Division', 'New Order',
        'The Cure', 'Depeche Mode', 'Sonic Youth', 'Pixies', 'My Bloody Valentine',
        'Slowdive', 'Cocteau Twins', 'Pavement', 'Sebadoh', 'Guided by Voices',
        'Neutral Milk Hotel', 'Elliott Smith', 'Nick Drake', 'Leonard Cohen', 'Tom Waits',
        'Captain Beefheart', 'Frank Zappa', 'King Crimson', 'Yes', 'Genesis (banda)',
        'Rush', 'Gentle Giant', 'Van der Graaf Generator', 'Can', 'Neu!',
        'Faust', 'Tortoise', 'Godspeed You! Black Emperor', 'Sigur Rós', 'Mogwai',
        'Tom Zé', 'Arnaldo Antunes', 'Itamar Assumpção', 'Walter Franco', 'Lupicínio Rodrigues',
      ],
    ),
  },
  {
    id: 'super-herois',
    emoji: '🦸‍♂️',
    nome: 'Super-heróis',
    descricao: 'Heróis da Marvel, DC e outros universos.',
    quantidade: 150,
    cartas: cartas(
      [
        'Homem-Aranha', 'Batman', 'Superman', 'Mulher-Maravilha', 'Capitão América',
        'Homem de Ferro', 'Thor', 'Hulk', 'Viúva Negra', 'Gavião Arqueiro',
        'Pantera Negra', 'Doutor Estranho', 'Feiticeira Escarlate', 'Visão', 'Homem-Formiga',
        'Vespa', 'Senhor das Estrelas', 'Gamora', 'Drax', 'Rocket Raccoon',
        'Groot', 'Wolverine', 'Ciclope', 'Jean Grey', 'Tempestade',
        'Vampira', 'Noturno', 'Fera', 'Flash', 'Aquaman',
        'Lanterna Verde', 'Ciborgue', 'Arqueiro Verde', 'Caçador de Marte', 'Shazam',
        'Asa Noturna', 'Batgirl', 'Supergirl', 'Demolidor', 'Justiceiro',
        'Deadpool', 'Coisa', 'Tocha Humana', 'Homem-Invisível', 'Mulher Invisível',
        'Motoqueiro Fantasma', 'Homem de Gelo', 'Estrela Polar', 'Coloso', 'Kitty Pryde',
      ],
      [
        'Namor', 'Adam Warlock', 'Capitã Marvel', 'Miss Marvel', 'Poderosa',
        'Falcão', 'Máquina de Combate', 'Scott Lang', 'Hope van Dyne', 'Gambit',
        'Longshot', 'Jubileu', 'Homem-Aranha 2099', 'Homem-Aranha Negro', 'Venom',
        'Carnificina', 'Duende Verde', 'Doutor Octopus', 'Rinoceronte', 'Abutre',
        'Mysterio', 'Camaleão', 'Kingpin', 'Elektra', 'Punho de Ferro',
        'Luke Cage', 'Jessica Jones', 'Robin', 'Asa Negra', 'Estelar',
        'Besouro Azul', 'Fogo', 'Gelo', 'Zatanna', 'Doutor Destino',
        'Charada', 'Pinguim', 'Hera Venenosa', 'Espantalho', 'Bane',
        'Coringa', 'Duas-Caras', 'Arlequina', 'Exterminador', 'Moon Knight',
        'Shang-Chi', 'Surfista Prateado', 'Gavião Arqueiro Kate Bishop', 'Static Shock', 'Booster Gold',
      ],
      [
        'Namora', 'Sentinela', 'Patriota', 'Wonder Man', 'Nova',
        'Adão Vermelho', 'Firestorm', 'Átomo', 'Elasti-Girl', 'Metamorfo',
        'Robotman', 'Homem Negativo', 'Crazy Jane', 'Animal Man', 'Monstro do Pântano',
        'John Constantine', 'Doutor Fate', 'Gavião Negro', 'Mulher-Gavião', 'Steel',
        'John Stewart', 'Gato Selvagem', 'Sr. Terrífico', 'Power Girl', 'Caçadora',
        'Comissário Gordon', 'Alan Scott', 'Stargirl', 'Kang, o Conquistador', 'Ultron',
        'M.O.D.O.K.', 'She-Hulk', 'Songbird', 'Soldado Invernal', 'U.S. Agent',
        'Batwoman', 'Blue Marvel', 'Miss América', 'Pavitr Prabhakar', 'Homem-Aranha Noir',
        'Peni Parker', 'Silk', 'Ben Reilly', 'Blade', 'Batwing',
        'Signal', 'Azrael', 'Capuz Vermelho', 'Hush', 'Killer Croc',
      ],
    ),
  },
  {
    id: 'campeoes-lol',
    emoji: '⚔️',
    nome: 'Campeões de LoL',
    descricao: 'Todos os campeões de League of Legends.',
    quantidade: 170,
    cartas: cartas(
      [
        'Aatrox', 'Ahri', 'Akali', 'Alistar', 'Amumu',
        'Annie', 'Ashe', 'Blitzcrank', 'Braum', 'Caitlyn',
        'Darius', 'Dr. Mundo', 'Draven', 'Ekko', 'Evelynn',
        'Ezreal', 'Fiora', 'Garen', 'Gragas', 'Irelia',
        'Jax', 'Jayce', 'Jhin', 'Jinx', "Kai'Sa",
        'Karthus', 'Katarina', 'Kayn', "Kha'Zix", 'Lee Sin',
        'Leona', 'Lucian', 'Lulu', 'Lux', 'Malphite',
        'Master Yi', 'Miss Fortune', 'Mordekaiser', 'Morgana', 'Nami',
        'Nasus', 'Nautilus', 'Nunu & Willump', 'Pyke', 'Rammus',
        'Rengar', 'Riven', 'Sett', 'Shaco', 'Singed',
        'Soraka', 'Teemo', 'Thresh', 'Twisted Fate', 'Vayne',
        'Veigar', 'Vi', 'Warwick', 'Yasuo', 'Yone',
        'Yuumi', 'Zed',
      ],
      [
        'Akshan', 'Ambessa', 'Anivia', 'Aphelios', 'Aurelion Sol',
        'Azir', 'Bard', 'Brand', 'Camille', 'Cassiopeia',
        "Cho'Gath", 'Diana', 'Elise', 'Fiddlesticks', 'Fizz',
        'Galio', 'Gangplank', 'Gnar', 'Graves', 'Hecarim',
        'Heimerdinger', 'Janna', 'Jarvan IV', 'Karma', 'Kassadin',
        'Kayle', 'Kindred', "Kog'Maw", 'LeBlanc', 'Lissandra',
        'Malzahar', 'Maokai', 'Mel', 'Neeko', 'Nidalee',
        'Nocturne', 'Olaf', 'Orianna', 'Ornn', 'Pantheon',
        'Poppy', 'Rakan', 'Renekton', 'Ryze', 'Samira',
        'Sejuani', 'Senna', 'Seraphine', 'Shen', 'Shyvana',
        'Sion', 'Sivir', 'Sona', 'Sylas', 'Syndra',
        'Tahm Kench', 'Talon', 'Taric', 'Tristana', 'Tryndamere',
        'Twitch', 'Varus', 'Viego', 'Viktor', 'Vladimir',
        'Wukong', 'Xin Zhao', 'Zeri', 'Ziggs', 'Zoe',
      ],
      [
        'Aurora', "Bel'Veth", 'Briar', 'Corki', 'Gwen',
        'Hwei', 'Illaoi', 'Ivern', 'Kalista', 'Kennen',
        'Kled', "K'Sante", 'Lillia', 'Milio', 'Naafiri',
        'Nilah', 'Qiyana', 'Quinn', "Rek'Sai", 'Rell',
        'Renata Glasc', 'Rumble', 'Skarner', 'Smolder', 'Swain',
        'Taliyah', 'Trundle', 'Udyr', 'Urgot', "Vel'Koz",
        'Vex', 'Volibear', 'Xayah', 'Xerath', 'Yorick',
        'Zac', 'Zilean', 'Zyra',
      ],
    ),
  },
]
